//
// Copyright (c) 2024, 2025 NVI, Inc.
//
// This file is part of the FSL11 Linux distribution.
// (see http://github.com/nvi-inc/fsl11).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= AUID Account Customization
Chip Frock, Chevo Terrazas, and Ed Himwich
Version 1.2.1 - March 2025

:sectnums:
:experimental:
:toc:
:sectnums!:
== Document revision history

Click the "`Details`" toggle below for the revision history.

[%collapsible]
====

* 1.2.1 -- Add instructions for quad display; add missing final "`s'"
to a few "`Xresource`"

* 1.2.0 -- Minor release

* 1.1.6 -- Add collapsible box for document revision history

* 1.1.5 -- Add: CAPI certificate setup and use, disabling remote X11
connections, and promoting to _oper_ on connecting

* 1.1.4 -- Add display specific Xresources for remote

* 1.1.3 -- Add testing `login shell` window configuration

* 1.1.2 -- Clarify which lines to change in _.profile_

* 1.1.1 -- Add allowing for PC firewall and revision history

* 1.1.0 -- Initial version

====

:sectnums:
== Introduction

This document covers customization for AUID (login) user accounts. As
written, it describes customization of the _oper_ account for AUID
users on CIS hardened FSL11 systems (see the <<cis-setup.adoc#,CIS
hardening for FSL11>> document), but it can adapted for use in other
situations. Possible adaptations including:

* Using this approach with the _prog_ account in addition to _oper_.
The adaption should essentially be trivial.

* Using different _.Xresources_ files for different remote connections
for one AUID user. To fully automate this you may want to set an
environment variable when connecting and use that to select the
_.Xresources_ (and other) file(s) used.

* Using this approach with non-CIS hardening systems by adding
non-_oper_ (and non-_prog_) login accounts that can promote to being
_oper_ with _oper_account_ (and _prog_ with _prog_account_) as for
AUID accounts with CIS hardening (see the
<<cis-setup.adoc#_enabling_user_promotion_to_operprog_and_root,Enabling
user promotion to oper/prog and root>> section of the
<<cis-setup.adoc#,CIS hardening for FSL11>> document for the details).

* On non-CIS hardened systems without creating new accounts, providing
special aliases (in _~/.bash_alias_) to allow users to load different
_.Xresources_ files with one type-in. The _rlxr_ alias can be used as
a starting point for new aliases. There could also be aliases for
running different versions of the _.profile_ (starting alias _rl_) and
_.bashrc_ (starting alias _rc_) scripts.

For remote connections, detailed instructions are provided for the
connection client currently used on PCs by stations with AUID
accounts. The instructions could be adapted to other clients.

Two main areas are covered in this document:

* <<rc file customization>> -- Customizations in AUID specific
versions of _oper_'s  _.profile_ and _.bashrc_ files

* <<X11 resources customization>> -- Customizations of _xterm_ window
placements and sizes

There are four appendices related to connections from a PC:

* <<Create Client Session on a PC>> -- This is useful for connecting
to the FS computer from a PC.

* <<Enable SSH Key Login from a PC>> -- This can be used to streamline
logging into the FS computer from a PC.

* <<Create a connection through a jumpbox with a CAPI certificate from a PC>>
-- This explains how to setup using a CAPI key for a connection
through a jumpbox.

* <<Launch the FS from a PC>> -- This covers how to start the FS
when connecting from a PC.

== rc file customization

With the standard AUID configuration (see
<<cis-setup.adoc#\_adding_auid_accounts,Adding AUID accounts>> in the
<<cis-setup.adoc#,CIS hardening for FSL11 document>>, there are two
__rc__ (__run command__) files that can be used for customization of
the __oper__ account: __~oper/.profile_<AUID>__ and
__~oper/.bashrc_<AUID>__ (where __<AUID>__ is the user's AUID account
name). These files are described below. You may find it instructive to
look at the normal __~oper/.profile__ and __~oper/.bashrc__ files to
understand how they are typically used.

=== ~oper/.profile_<AUID>

This script is run for the _<AUID>_ user at end of the
_~oper/.profile_ script. As such, it is run only for interactive login
shells. It is the appropriate place to set session wide environment
variables and perform one-time login tasks. Since it is run at the end
of _~oper/.profile_, it can effectively override many things done by
_~oper/.profile_.

=== ~oper/.bashrc_<AUID>

This script is run for the _<AUID>_ user at end of the _~oper/.bashrc_
script. As such, it is run only for interactive shells, both login and
non-login. It is the appropriate place to set shell interactive
information such as shell options, prompts, and command aliases. Since
it is run at the end of _~oper/.bashrc_, it can effectively override
many things done by _~oper/.bashrc_.

NOTE: _.bashrc_ is run at the start of _.profile_ for login shells.

An example of using this file for the _sysadmin_'s AUID account is
given in the <<cis-setup.adoc#_setting_hostname_alias,Setting hostname
alias>> section of the
<<cis-setup.adoc#_additional_items_for_fs_operations,Additional items
for FS operations>> appendix of the <<cis-setup.adoc#,CIS hardening
for FSL11>> document.

== X11 resources customization

This section provides procedures for customizing FS _xterm_ window
placement and size using X11 resources files. This may be useful for
defining different window configurations on the console or when
connecting over _ssh_ from a remote device, which may have a different
display size.

There are two ways to customize X11 resources, either use the same
customization for all users, i.e., _general_, or different ones, _per
AUID account_. The approaches can be mixed so some users get the
general setup and others get an individual setup.

The methods given here will _not_ work for programs that aren't
_xterm_ based.  In particular, the RDBE monitor and _rdbemsg_ programs
positions cannot be set this way, but have their own options for
setting their geometries. Those options may be used on the lines for
the programs in the _/usr2/control/clpgm.ctl_ file for the
`*client=...*` command and in the _~/.fvwm2rc_ file for hot-keys and
menu options on the local console. Likewise, the appropriate line must
be modified to explicitly set a geometry for a basic _xterm_ window
opened with the `*client=xterm*` command or with the window manager.
Different layouts can be supported with different commands (lines) in
the files. With additional changes, it would also be possible to use
different _~/.fvwm2rc_ files for different users on the local console.

The naming convention for the X11 resources files in _~oper_ is:

* _.Xresources_ -- General local values

* _.Xresources_remote_ -- General remote values

* __.Xresources_<AUID>__ -- Per AUID local values for account _<AUID>_

* __.Xresources_remote_<AUID>__ -- Per AUID remote values for account _<AUID>_

* __.Xresources_remote_<AUID>_<display>__ -- Per AUID remote values
for _<display>_ for account _<AUID>_

=== General X11 resources customization

The section provides procedures for customing the X11 resources so they
are the same for all AUID users. The customization can be different
for local and remote users; each is covered in sub-sections below.
They can be combined with
<<Per AUID account X11 resources customization>> to tailor the
configuration for those users that want to deviate from the general
one.

==== General X11 resources customization for a local connection

. Login in on the console with your AUID account.

. Enter the commands:

 mv .Xresources .Xresources.orig
 ln -sfn ~oper/.Xresources .Xresources

. Start the GUI by entering `*oper_x11*`.

.. Working in the `login shell` window:

... Enter your password when prompted.

... Start the FS: `*fs*`

.... Adjust the windows to the sizes and positions you want.

+

+

This can include the `login shell` window.

.... Open an additional window to work in, e.g., use `*client=xterm*` in
the `Operator Input` window

..... Adjust the contents of ~oper/_.Xresources_ using the method of
https://nvi-inc.github.io/fs/releases/misc/install_reference.html#_setting_geometry_values_in_xresources[Setting
geometry values in .Xresources].

+

TIP: Copying text by dragging the mouse over it with the first button
depressed and pasting with the middle mouse button may work best.

+

TIP: To test the settings for the `login shell` window, it will
necessary to exit from the GUI and restart it with `*oper_x11*`.

+

+

+

+

+

NOTE: The referenced method is a section of the FS "`Installation
Reference Document`"
(https://nvi-inc.github.io/fs/releases/misc/install_reference.html).

..... Enter `exit` to close the additional window.

.... Terminate the FS (or client)

... Exit from the `oper` account shell.

... Exit from the AUID account shell (and `login shell` window).

. Login in on the console with your AUID account.

.. Working in the `login shell` window:

... Promote to _oper_ using the _oper_account_ command.

... Enter your password when prompted.

... Start the FS: `*fs*` (or client: `*fsclient*`)

+

+

+

The windows should appear as you set them. If not, you may need to
iterate adjusting the _~oper/.Xresources_ file.

==== General X11 resources customization for a remote connection from a PC

This procedure assumes that you have created a client session for
connecting to the FS computer on the PC according to the appendix
<<Create Client Session on a PC>>.

CAUTION: Before starting, you may want to make sure the PC has the
display set to 100% scaling (this may require logging out and logging
in again) and the Taskbar is set to automatically hide. This will give
more screen space to work with.

. In the connection client program on the PC, double-click on the
session you will be using.

.. Enter your password if prompted for it. If prompted to save your
password, click `No`.

.. Working in the `login shell` window:

... Promote to _oper_ using the _oper_account_ command.

... Enter your password when prompted.

... Start the FS: `*fs*`

.... Adjust the windows to the sizes and positions you want.

+

+

+

This can include the `login shell` window.

.... Open an additional window to work in, e.g., use `*client=xterm*` in
the `Operator Input` window

..... Edit the _~oper/.profile_ file:

+

Change the `xrdb -merge ...` line for a _remote_ connection. This is
the first one in the file. The following lines show the preceding
comment to help identify it. Only the second line needs to be
modified.  Change:

+
....
#       ssh from remote host with X display
        xrdb -merge ~/.Xresources
....

+

to:

+
....
#       ssh from remote host with X display
        xrdb -merge ~/.Xresources_remote
....

..... If you have not already created the  general file
_.Xresources_remote_ file according to <<quad,Quad Display>> create
one by copying the nominal file:

  cp .Xresources .Xresources_remote

..... If needed, adjust the contents of _~oper/.Xresources_remote_
using the method of
https://nvi-inc.github.io/fs/releases/misc/install_reference.html#_setting_geometry_values_in_xresources[Setting
geometry values in .Xresources].

+

[TIP]
====

Copying text by dragging the mouse over it with the first button
depressed and pasting with the middle mouse button may work best.

For testing the configuration for all windows except `login shell`,
instead of using the _rlxr_ alias, use the command:

 xrdb -merge ~oper/.Xresources_remote

and restart the FS. To test for `login shell`, it will necessary to
log-out of the AUID session completely and log back in again.

====

+

+

+

+

+

NOTE: The referenced method is a section of the FS "`Installation
Reference Document`"
(https://nvi-inc.github.io/fs/releases/misc/install_reference.html).

..... Enter `Exit` to close the additional window.

.... Terminate the FS (or the client)

... Exit from the _oper_ account shell

... Exit from the AUID account shell (and `login shell` window).

. Press kbd:[Enter] (in the session tab: to close it).

. Right-click on the session you are using.

.. Click `Edit session`

... Click `Advanced SSH settings`

.... Change the `xrdb` command part of the `Execute command:` text box
(the part before the semi-colon, `;`) to:

 xrdb -merge ~oper/.Xresources_remote

+

+

+

+

+

CAUTION: The changes are to the path _and_ name of the X11 resources file.

.. Click `OK`

. Double-click on the session you are working with.

.. Enter your password if prompted for it. If prompted to save your
password, click `No`.

.. Working in the `login shell` window:

... Promote to _oper_ using the _oper_account_ command.

... Enter your password when prompted.

... Start the FS: `*fs*` (or client: `*fsclient*`)

+

+

+

The windows should appear as you set them. If not, you may need to
iterate adjusting the _~oper/.Xresources_remote_ file.

=== Per AUID account X11 resources customization

The steps in this introductory section only need to be done once. For
each user that wants individualized settings, use the steps in the
sub-sections below for local and remote connections as appropriate.

. Login on the console with your AUID account _or_ double-click on the
session in the connection client on the PC.

+

If you are working from a PC, you must have already setup the session
according to the appendix <<Create Client Session on a PC>>.

. Working in the `login shell` window:

.. Promote to _oper_ with the _oper_account_ command.

.. Enter your password when prompted.

.. If the _oper_ account has _not_ already been setup according to
<<General X11 resources customization for a remote connection from a PC>>
or a _.Xresources_remote_ file created according to
<<quad,Quad Display>>, create the general file for remote by copying
the nominal file:

  cp .Xresources .Xresources_remote

.. Edit the file _~oper/.profile_ to make two changes:

...  Change the `xrdb -merge ...` line for a _remote_ connection.

+

This is the first one in the file. The following lines show the
preceding comment to help identify it. Only the second line needs to
be modified. Change:

+

CAUTION: If the _oper_ account has _not_ already been setup according
to
<<General X11 resources customization for a remote connection from a PC>>,
the old line will have `~/.Xresources` instead of
`~/.Xresources_remote`. Replace it anyway.

+
....
#       ssh from remote host with X display
        xrdb -merge ~/.Xresources_remote
....

+

to:

+
....
#       ssh from remote host with X display
        if [ -f "$HOME/.Xresources_remote_$SUDO_USER" ]; then
          xrdb -merge ~/.Xresources_remote_$SUDO_USER
        else 
          xrdb -merge ~/.Xresources_remote
        fi
....

...  Change the `xrdb -merge ...` line for a _local_ connection.

+

This is the last one in the file (the third including the one added
above). The following lines show the preceding comment to help
identify it. Only the second line needs to be modified. Change:

+
....
#       login shell (because this is .profile) on the local X console
        xrdb -merge ~/.Xresources
....

+

to:

+

+

+
....
#       login shell (because this is .profile) on the local X console
        if [ -f "$HOME/.Xresources_$SUDO_USER" ]; then
          xrdb -merge ~/.Xresources_$SUDO_USER
        else
          xrdb -merge ~/.Xresources
        fi
....

.. Enter `exit` to close the _oper_ account shell

.. Exit from the AUID account shell (and `login shell` window).

. If you connected from a PC, press kbd:[Enter] (in the session tab:
to close it).

==== Per AUID account X11 resources customization for a local connection

CAUTION: This procedure uses _dhorsley_ as an example AUID (login)
account name. You should substitute your login account name wherever
_dhorsley_ is used.

Except for the three items below, follow the same procedure as in
<<General X11 resources customization for a local connection>>:

. Just after logging into the AUID account, _dhorsley_ for this
example, execute:

+

CAUTION: If the _oper_ account has already been setup according to
<<General X11 resources customization for a local connection>>,
do _not_ use the `mv` command below.

 mv .Xresources .Xresources.orig
 ln -sfn ~oper/.Xresources_dhorsley .Xresources

. When the additional window is opened, e.g., with `*client=xterm*`:

.. Copy the nominal file:

  cp .Xresources .Xresources_dhorsley

.. Adjust the contents of _~oper/.Xresources_dhorsley_ instead of
_~oper/.Xresources_.

+

For testing the configuration for all windows except `login shell`,
instead of using the _rlxr_ alias, you can use the command:

 xrdb -merge ~oper/.Xresources_dhorsley

+

+

and restart the FS. To test the settings for the `login shell` window,
it will necessary to exit from the GUI and restart it with
`*oper_x11*`.

. If you need to iterate, adjust the file _~oper/.Xresources_dhorsley_.

==== Per AUID account X11 resources customization for a remote connection from a PC

CAUTION: This procedure uses _dhorsley_ as an example AUID (login)
account name. You should substitute your login account name wherever
_dhorsley_ is used.

CAUTION: This procedure assumes you are setting this up for a _quad_
display as described at <<quad,Quad Display>>. If you are doing it for
say, your laptop, you can use _laptop_ in place of _quad_ in the
instructions below. You can have both quad and laptop (and other
additional) configurations for a given AUID user. This is helpful if
you connect from different machines with different X11 resolutions or
display sizes.

TIP: If you are only making a non-display specific Xresources file,
e.g., _~oper/.Xresources_remote_dhorsley_ for this user, drop the
__quad_ in the instructions below and skip making the dummy
_~oper/.Xresources_remote_dhorsley_ file.

Except for the three items below, follow the same procedure as in
<<General X11 resources customization for a remote connection from a PC>>:

. When the additional window is opened, e.g., with `*client=xterm*`:

.. Do _not_ edit the _~oper/.profile_ file.

.. Do _not_ copy to create the general remote file.

.. Instead, copy the general remote file to create the AUID remote
file for this display:

  cp .Xresources_remote .Xresources_remote_dhorsley_quad

.. Create a dummy _.Xresources_remote_dhorsley_ file:

+

TIP: Skip this sub-step if you are making a non-display specific
Xresources file for this user.

+

NOTE: Since the display specific Xresources are set by the command
that the PC client uses, this sub-step prevents the Xresources from
being overwritten and removes additional (redundant) communication
with the X11 server.

 cat <<EOT >.Xresources_dhorsley
 !if this file has no resources look for other .Xresources_remote_* files for this AUID
 EOT

.. Adjust the contents of _~oper/.Xresources_remote_dhorsley_quad_
instead of _~oper/.Xresources_remote_.

+

For testing the configuration of all windows except `login shell`, the
_rlxr_ alias will not reload its resources, but you can use the
command:

 xrdb -merge ~oper/.Xresources_remote_dhorsley_quad

+

+

and restart the FS. To test for `login shell`, it will necessary to
log-out of the AUID session completely and log back in again.

. When changing the `xrdb` command part of the `Execute command:` text
box (the part before the semi-colon, `;`), make it:

 xrdb -merge ~oper/.Xresources_remote_dhorsley_quad

+

CAUTION: The changes are to the path _and_ name of the X11 resources file.

. If you need to iterate, adjust the file
_~oper/.Xresources_remote_dhorsley_quad_.

[appendix]
== Create Client Session on a PC

Details interactions are provided for the connection client used by
stations that connect from PCs.

If you will be connecting with a CAPI certificate through a jumpbox,
follow the directions in the
<<Create a connection through a jumpbox with a CAPI certificate from a PC>>
appendix before using these instructions.

CAUTION: This procedure uses _dhorsley_ as an example login account
name. You should substitute your login account name wherever
_dhorsley_ is used.

NOTE: The first time you run the client connection program, you will
probably be prompted by the firewall about whether to allow
connections for its X11 server. If so, click `Allow`. Then you may be
prompted about whether to allow the firewall to make changes. If so,
click `Yes`.

. In the client connection program on the PC, click `Session`

.. Click `SSH`

... Use the IP address of the FS computer for the `Remote host *`.

... Check the `Specify username` box, and supply the AUID account
name, `dhorsley` (for this example).

... Click `Advanced SSH settings`

.... Make sure the `X11-Forwarding` box is checked.

.... Make sure the `Remote environment:` is `Interactive shell`.

.... In the `Execute command:` text box, enter:

 xrdb -merge ~/.Xresources ; xterm -ls -name login_sh

+

TIP: If you want this session to directly promote to _oper_, add
`{nbsp}-e{nbsp} oper_account` to the end of the command (note the
required leading space `{nbsp}`, in the string to be added). When
connecting, it will be necessary to enter the AUID account password
when prompted by _sudo_ to promote to _oper_.

+

+
[NOTE]
====

[[quad]]<<quad,Quad Display>>: If your FS display uses four monitors,
a _quad_ display (an arrangement that  provides much more screen real
estate), you may want to use a slightly different approach. Please
click on the "`Details`" toggle below for more information.

[%collapsible]
=====

In the `Execute command:` text box, enter instead:

 xrdb -merge ~oper/.Xresources_remote ; bash

This command will open a _bash_ shell prompt on the target machine.
From there, you can open __xterm__s that will be sized and positioned
according to the _oper_ Xresources file (which must be installed, see
below). For example, you can define Xresources for a window named
`xterm_2` and start such an _xterm_ with:

 xterm -name xterm_2 &

If you promote to _oper_ before opening the _xterm_, it will run in
the _oper_ account instead of the AUID account.

Example files for use with a quad display are included in
_/root/fsl11/quad_display/_:

[disc]
* _fsy_ -- A script to open a `login shell` running the FS, or running
the client if the FS is already running. It is intended to be run
after promoting to _oper_ in the _bash_ shell session opened by the
connection.

* _xterm_2_ -- A script to open an _xterm_ with the name `xterm_2`.
This is also intended to be run from the _bash_ shell session opened
by the connection, but it may be before or after promoting to _oper_
depending on what is needed.

* _.Xresources_remote_ -- An example quad display Xresources file that
includes example window lay-outs, including for `xterm_2`.

The scripts can be placed in _~oper/bin_ by _root_:

  cd ~oper/bin
  cp /root/fsl11/quad_display/fsy .
  cp /root/fsl11/quad_display/xterm_2 .
  chown oper.rtx fsy xterm_2
  chmod o-x fsy

The Xresources file can be placed in _~oper_ by _root_:

  cd ~oper
  cp /root/fsl11/quad_display/.Xresources_remote .
  chown oper.rtx .Xresources_remote

If the file already exists in _~oper_ you will be asked to confirm the
_cp_. If it is safe to overwrite, you can answer `*y*`. Working as _oper_, you
can modify the size and placement of the windows in
_~oper/.Xresources_remote_ as you wish.

Working as _oper_, you can setup additional __xterm__s: `xterm_3`,
etc,, either by cloning and modifying _~oper/bin/xterm_2_ or adding
them to that script. The resources for `xterm_2` in
_~oper/.Xresources_remote_ can be copied-and-pasted for each
additional _xterm_ and the copies modified.

=====

====
.... Make sure the `Do not exit after command ends` is _not_ checked.

... Click `Bookmark settings`

.... Optionally, change the `Session name:` to something more
meaningful, for this example: `fs1&#8209;12m` or
`dhorsley@fs1&#8209;12m`.

... If you will be using a CAPI certificate to connect through a
jumpbox, click on the *Details* toggle below for additional steps that
are needed.

+

[%collapsible]
=====

.... Click on `Network settings`

..... Click on `SSH gateway (jump host)`

...... Enter the jumpbox address in the `Gateway host` text box.

...... Enter your user name on the jumpbox in the `Username` text box

...... Enter the port (usually `22`) on the jumpbox in the `Port` text
box.

...... Check `Use SSH key`, but do not select a key file in the field
below it.

...... Click `OK`

NOTE: You can create tunnels for additional connections through the
jumpbox using the `Tunnels` menu in the top level of the client
connection program.  These tunnels can be started automatically when
you start the program by selecting the blue "`runner`" icon on the
corresponding line.

=====

... Click `OK`

+

+

+

The client will attempt to connect.

.. If you are asked to accept the connection (maybe `connexion`) and
the displayed IP address is  correct, click `Accept`.

.. Enter your password when prompted. If prompted to save your
password, click `No`.

+

+

The `login shell` window should appear, but it may be oddly
placed/sized.

.. Working in the `login shell` window:

... Enter `exit`.

. Press kbd:[Enter] (in the session tab: to close it).

. For improved security, click `Settings`

.. Click `X11`

... For `X11 remote access`, select `disabled`.

.. Click `OK`


[TIP]
====

You can create a desktop shortcut to open the connection. In the
connection client:

. Select the `Sessions` icon.

. Right-click on the session from the drop-down list and select `Edit
session`.

. Select `Create a desktop shortcut to this session`

. Check both `Hide terminal on startup` and `Close ... on exit`
boxes and select `OK`.

. If you are using the <<quad,Quad Display>> approach above, in the
`Start session in` drop-down box select `Detached tab`.

. Select `OK`.

====

If you aren't using a CAPI certificate, please see the appendix
<<Enable SSH Key Login from a PC>> for a way to streamline logging in
without using a password. That is better than having the connection
client remember your password since that may change.

[appendix]
== Enable SSH Key Login from a PC

If you are not using a CAPI certificate, you can avoid the need to
enter your password each time you login by using an _ssh_ key. The key
will work across password changes, but will not work if the password
has expired.

NOTE: You will still need to use your password to promote to _oper_ on
the FS machine.

This procedure assumes that you have created a client session for
connecting to the FS computer on the PC according to the appendix
<<Create Client Session on a PC>>.

. In the PC connection client program on the PC, click `Tools`

.. Click the option with `(SSH key generator)`

... Make sure `RSA` is selected for `Type of key to generate`.

... Make sure `2048` is entered for `Number of bits in a generated key`.

... Click `Generate`

+

+

+

Move the mouse around the _blank_ area to generate some randomness
until a key is displayed.

... Click `Save Private key`

.... When prompted, click `Yes` to confirm saving the key without a
passphrase.

.... Click the (your) `Documents` folder.

.... Enter a `File Name:` _id_rsa_. A _.ppk_ extension is added
automatically.

.... Click `Save`

... Use the mouse to copy the text in the `Public key for ...` field.

+

+

+

Select the _entire_ text (starting with `ssh-rsa` through the
`rsh-key-_YYYYMMDD_`) by dragging the mouse over it with the first
button depressed. You may need to drag downward to force scrolling in
the text box to get it all. Then enter kbd:[Control+C] to copy it.

... Close the window with the `X` in the upper right corner.

. Double-click on the session you want to connect to.

+

NOTE: If this method for transferring the public key, specifically the
pasting, doesn't work, you can try the <<alternate,Alternative>>
method in the *NOTE* below.

.. Enter your password when prompted.  If prompted to save your
password, click `No`.

.. Working in the `login shell` window:

... Enter:

  cat >>~/.ssh/authorized_keys

... Paste the copied text into the window by pressing the middle mouse
button.

... Press kbd:[Enter].

... Press kbd:[Control+D].

... Enter `exit` to close the connection to the FS computer.

. Press kbd:[Enter] (in the session tab: to close it).

+

[NOTE]
====

[[alternate]]<<alternate,Alternative>>: If the above method for
transferring the public key does not work, this may (click on
*Details* to open/close):

[%collapsible]
=====

. Click `Start local terminal`

.. Use _ssh_ to connect to the FS machine, using your AUID account
name instead of `dhorsley` and the FS machine's IP address in place of
`xxx.xxx.xxx.xxx`:


 ssh dhorsley@xxx.xxx.xxx.xxx

+

+

_ssh_ will attempt to connect.

.. If prompted to confirm the remote host's key, enter `yes`, unless
you have some reason to believe it is incorrect.

.. Enter your password when prompted.  If prompted to save your
password, click `No`.

.. In the connection to the FS, enter:

  cat >>~/.ssh/authorized_keys

.. Paste the copied text into the window with kbd:[Shift+Insert], or
right-click in the window and click `Paste`.

+

When right-clicking, if you are prompted to assign `Actions of mouse
buttons`, click `right-click action` as `Show context menu`, click
`OK` and then click `Paste` from the context menu.

+

+

If you are prompted for `... paste confirmation`, click `OK`.

.. Press kbd:[Enter].

.. Press kbd:[Control+D].

.. Enter `exit` to close the connection to the FS computer.

.. Enter `exit` to close the local terminal.

=====
====

. Right-click on the session where you will install the key (_fs1-12m_
in this example).

.. Click `Edit session`

... Click `Advanced SSH settings`

.... Make sure the `Use private key` box is checked.

.... Click on the _browse_ icon in the text entry field for `Use
private key`.

..... Double-click on the private key file you created, _id_rsa_
(`Type`: PuTTY Private Key File; extension _.ppk_) , in the (your)
_Documents_ directory.

... Click `OK`

. Test the connection, by double-clicking on the session.

+

The `login shell` window should appear.

.. Working in the `login shell` window:

... Enter `exit`.

. Press kbd:[Enter] (in the session tab: to close it).

[appendix]
== Create a connection through a jumpbox with a CAPI certificate from a PC

CAUTION: These instructions have not been verified, but should be
close to being correct. Please report any discrepancies.

. Run the _key agent_

+

For example, using the search box in the `Start` window, type
the name of the _key agent_, then select the displayed app.

. In the `Task bar`, in the `System Tray` (usually on the right side),
right-click on the _key agent_ icon. It looks like a computer/monitor
with a black-hat tilted to the right. If the icon is not displayed,
you may need to click the "`up`" arrow in the `System Tray` to show
all the apps. Once the app is display, right-click on it.

.. Select `Add CAPI Cert`

+

+

If a dialog box appears asking to confirm loading the
certificate/key, click `Ok` (or `Yes`).

. Right click on _key agent_ icon again

.. Select `View Keys & Certs`

... In the `... Key List` window, select the key, if it isn't already.

... Click on `Copy To Clipboard`

+

+

+

+

Mail the key to the system administrator of the jumpbox system. Wait
until you get confirmation from the system administrator that your key
has been installed before continuing. It may take several hours for
this to happen.

. After you receive confirmation from the jumpbox system administrator
that your key has been installed:

.. Following the directions in the first three steps above to add your
CAPI certificate (if it is no longer present) and copy it to the
clipboard.

.. Right click on _key agent_ icon again

... Click on `New Session`

.... Enter your jumpbox hostname (or IP) in the `Host Name (or IP
address)` text box.

.... Click on `Data` under `Connection` on the left side.

+

Enter your user name (perhaps your AUID) in the `Auto-login username`
text box

.... Click the plus sign,`+`, to left of `SSH` under `Connection` on
the left side.

.... Click on `Auth` under `SSH`

+

Make sure `Attempt authentication using Pagent` is checked.

.... Click on `Session` on the left side (at the top)

..... Enter a suitable name in the `Saved Sessions box` text box,
perhaps `jumpbox`

..... Click `Save`

..... Click `Open`

+

+

+

+

+

You should be prompted for your SmartCard PIN and then logged into a
jumpbox session.

...... From the jumpbox session, connect to your target host with `ssh`
using your user name for `_AUID_` (in fact, perhaps your AUID) and the
hostname (or IP) of the target host for `_target_`:

+

+

+

+

+

[subs="+quotes"]
....
 ssh _AUID_@_target_
....

+

+

+

+

+

+

Enter your password when prompted. That should log you into that
system.

...... On your target system, enter

 cat >>~/.ssh/authorized_keys

...... Paste the clipboard into the target system with kbd:[Ctrl+V].

......  Press kbd:[Enter].

...... End input to the _cat_ command with kbd:[Ctrl+D].

...... Exit from the target session: `exit`.

...... Exit from the jumpbox session: `exit`.

.. Right click on _key agent_ icon again

... Highlight the session for the jumpbox, perhaps `jumpbox`, under
`Saved Sessions`.

... Click `Load`

... Click on of `SSH` under `Connection` on the left side

+

+

+

Enter `exit` for the `Remote Command`

... Click on `Session` on the left side (at the top)

... Click `Save`

[appendix]
== Launch the FS from a PC

This procedure assumes that you have created a client session with
an _ssh_ key for login according to the appendix
<<Enable SSH Key Login from a PC>>.

It may be helpful to customize the windows according to the
<<General X11 resources customization for a remote connection from a PC>>
section in the main document above, but that is not necessary. It also
possible to customize them per AUID account for a remote connection as
described in the <<Per AUID account X11 resources customization>> section in
the main document.

. If you require a CAPI certificate to connect, it will need to be
loaded and you will need to enter your PIN each time after rebooting
(and possibly after removing and reinserting your SmartCard). Click
on the *Details* toggle below for the steps needed.

+

[%collapsible]
====

.. Run the _key agent_

+

+

For example, using the search box in the `Start` window, type
the name of the _key agent_, then select the displayed app.

.. In the `Task bar`, in the `System Tray` (usually on the right
side), right click on the _key agent_ icon. It looks like a
computer/monitor with a black-hat tilted to the right. If the icon is
not displayed, you may need to click the "`up`" arrow in the `System
Tray` to show all the apps.

... Select `Add CAPI Cert`

+

+

A dialog box will appear asking to confirm loading the
certificate/key, click `Ok` (or `Yes`).

..  Right-click the _key agent_ icon in the `System Tray` again.

... Select `Saved Sessions`, then select the appropriate session,
perhaps `jumpbox`.

+

+

A dialog box will appear prompting you for your PIN, enter it and
select `OK`.

+

A window for the connection will appear. If everything goes okay, it
will disappear. If it doesn't disappear, it may contain useful
information about what went wrong.

====

. In the PC connection client program on the PC, if you don't see the
list of `User sessions`, click the star (favorite) icon under `Quick
connect ...` on the left.

. Double-click on the session you will be using.

.. Working in the `login shell` window:

... Promote to _oper_ using the _oper_account_ command.

... Enter your password when prompted.

... Start the FS: `*fs*`

+

+

+

If the window placement isn't convenient, you can customize it using
the references above.

. To exit:

.. Working in the `login shell` window:

... Close the client with kbd:[Control+C].

+

+

+

Alternatively, you can `*terminate*` the FS.

... Enter `exit` to close the _oper_ shell.

... Exit from the AUID account shell (and `login shell` window).

. Press kbd:[Enter] (in the session tab: to close it).
