//
// Copyright (c) 2020-2022 NVI, Inc.
//
// This file is part of the FSL10 Linux distribution.
// (see http://github.com/nvi-inc/fsl10).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= CIS hardening for FSL11
:sectnums:
:experimental:
:toclevels: 3
:toc:
Dave Horsley and Ed Himwich
Version 0.0.5 - August 2022

== Introduction

These notes detail adding extra security features to Field System
Linux _11_, FSL11, as advised by Center for Internet Security (CIS).
This is provided as an option for sites that might need additional
security.

At the time of this writing, there is no CIS security benchmark for
Debian _11_, which is what FSL11 is based on. Instead, the latest
benchmark for Debian _10_ was used. Although this is not technically
correct, the changes in the benchmark for Debian _10_ compared to
Debian _9_ were relatively minor; primarily removal of items. It seems
plausible that the Debian _10_ benchmark will be adequate for Debian
_11_. In fact, all of the items that fail for FSL11 are either things
that are required for  FS operation, items that appear to actually be
secure despite the benchmark not recognizing them as such, and one
change since Debian _10_ that we worked around.  However, we don't
know what additional checks will be in the Debian _11_ benchmark.

[NOTE]
====

Additional steps needed to use the benchmark:

. Install the package `default-jre` with _apt-get_.

. Disable the _java_ version check in _CIS-CAT.sh_.

. Change `ignore.platform.mismatch` to `true` in
_misc/ciscat.properties_.

====

With the exception of the partition configuration, all actions are to
be performed post-installation (see the <<installation.adoc#,FSL11
Installation>> document). Applying the remediations, the exceptions
that are still present, all tests that failed, and problems with the
benchmark remediations are provided in separate sections below. An
appendix covers additional setup that is needed for FS operations
after the remediations have been applied.

This document  is based on the results for the "`CIS Debian Linux 10
Benchmark v1.0.0 - Level 2 - Server`".

== Applying CIS remediations

=== Installation partition configuration

During installation, be sure to create the logical volumes marked
optional in the partition setup section.

=== Post-installation remediations

All commands need to be run as _root_.

==== Scripted remediations

As many remediations as possible are implemented by the _remediate_
script.  The script is intended to be run after the "`Third Stage
Installation`" steps in the FSL11 instructions, before any further
changes have been made to the system (however initializing and adding
other disks to the RAID can intervene).

....
cd /root/fsl11
script ../remediate.txt
./remediate
exit
....

IMPORTANT: This script should not be run more than once on a system.

TIP: The use of the _script_ command causes the output to be recorded
in the specified file. This can be very helpful for understanding what
went wrong if the script fails. The script itself uses the `-x` option
to echo the commands as they are executed to make it easy to match the
output with the commands being executed.

==== Reboot

The system should be rebooted to make sure all the remediations have
been applied. Some aren't enforced until a reboot.

After the reboot, all the CIS remediations that can applied at this
point have been completed. The next subsection describes some other
policies that can be considered.

=== CIS issues that need to be addressed

:sectnums!:

This section lists further topics related to the benchmark that should
be discussed. The items are listed by benchmark section numbers.

==== 1.5.2 Ensure bootloader password is set

You may wish to create an encrypted password with
grub-mkpasswd-pbkdf2:

....
grub-mkpasswd-pbkdf2
Enter password: <password>
Reenter password: <password>
Your PBKDF2 is <encrypted-password>
....

Add the following into  a custom _/etc/grub.d_ configuration file
(don't use _/etc/grub.d/00_header_ as it can be overwritten by a
package update):

....
cat <<EOF
set superusers="<username>"
password_pbkdf2 <username> <encrypted-password>
EOF
....

If there is a requirement to be able to boot/reboot without entering
the password, edit _/etc/grub.d/10_linux_ and add `--unrestricted` to the
line `CLASS=`

IMPORTANT: It is strongly recommended that booting without a password
be permitted. Otherwise, if a reboot is required to continue
operations it will not be possible unless some one with the password
is available. If they aren't available, this could lead to a safety
issue or loss of VLBI data.

Example:

....
CLASS="--class gnu-linux --class gnu --class os --unrestricted"
....

Run the following commands to update the grub2 configuration and reset
the _grub.cfg_ permissions:

....
update-grub
chmod go-rwx /boot/grub/grub.cfg
....

==== 1.8.1.2 Ensure the local login warning banner is configured properly

You may want to update _/etc/issue_ to have a more tailored message
with sterner warnings. The message must not include use of `\m`, `\r`,
`\s`, `\v`, or references to the OS platform.

==== 1.8.1.3 Ensure the remote login warning banner is configured properly

You may want to update _/etc/issue.net_ to have a more tailored
message with sterner warnings. The message must not include use of
`\m`, `\r`, `\s`, `\v`, or references to the OS platform.

==== 1.8.2 Ensure GDM login banner is configured properly

You may want to update _/etc/gdm3/greeter.dconf-defaults_ to have a
more tailored message with sterner warnings.

If desired, you can remove the Debian logo from the GUI login page by
renaming the file specified for the `logo` option of the
`[org/gnome/login-screen]` section in
_/etc/gdm3/greeter/dconf-defaults_. For example, if appropriate, you
might use:

 cd /usr/share/images/vendor-logos
 mv logo-text-version-64.png logo-text-version-64.png.bak

If desired, you can remove the Debian logo from the _grub_ menu by
renaming the file specified for in the `if` clause for the
`background_image` file in the `/etc/grub.d/05_debian_theme` section
of _/boot/grub/grub.cfg_. For example, if appropriate, you might use:

 cd /usr/share/desktop-base/homeworld-theme/grub
 mv grub-4x3.png grub-4x3.png.bak

[IMPORTANT]
====

Caveat Emptor! The changes below in this *IMPORTANT* section may not
be safe. Even if they appear to be successful, they may case problems
later. The problems may include failure of automatic updates. They may
also need to be reinstalled after updates.

After making any or all of these changes, it is necessary to execute:

 update-grub

for them to take effect.

. In principle, you can remove the `Debian` label from the _grub_ boot
menus by editing _/etc/default/grub_ and inserting a line:

 GRUB_DISTRIBTOR=FSL11

+

immediately after the existing `GRUB_DISTRIBUTOR=...` line.

. In principle, you can remove the `GNU/Linux` label from the _grub_
boot menus by editing _/etc/grub.d/10_linux_ and inserting a line:

 OS="${GRUB_DISTRIBUTOR}"

+

immediately after the existing `OS="${GRUB_DISTRIBUTOR} GNU/Linux"`
line.


. In principle, you can remove the `Linux` label from the lines
displaying kernel image files, by editing _/etc/grub.d/10_linux_ and
globally replacing `{nbsp}Linux{nbsp}` (not the single leading and
single trailing spaces) with `{nbsp}FSL11{nbsp}` (not the single
leading and single trailing spaces).

====

==== 2.2.1.4 Ensure ntp is configured

This needs the  FS NTP configuration. That is more secure than the
benchmark since it uses `ignore` by default.

==== 4.1.2.3 Ensure system is disabled when audit logs are full

This may not be appropriate for an operational system.

==== 4.2.1.5 Ensure rsyslog is configured to send logs to a remote host

To set a remote log host, edit the _/etc/rsyslog.conf_ and/or the
_/etc/rsyslog.d/*.conf_ files and add lines like the following
(replace angle bracket items, `<...>`, with your values):

....
<files to sent to the remote log server> action(type="omfwd" target="<FQDN or ip of loghost>" port="<port number>" protocol="tcp"
action.resumeRetryCount="<number of re-tries>"
queue.type="linkList" queue.size=<number of messages to queue>")
....

or

....
*.* @@<FQDN or ip of loghost>
....

Run the following command to reload the _rsyslog_ configuration:

....
systemctl reload rsyslog
....

==== 5.2.16 Ensure SSH Idle Timeout Interval is configured

Five minutes is too short and is not commensurate with the recommended
15 minute auto-logout interval.

==== 5.3.1 Ensure password creation requirements are configured

Should the minimum be reduced to 12 characters?

==== 5.3.2 Ensure lockout for failed password attemtps is enabled

The number of login failures before lock-out can cause a problem if it
is set too low. The main issue is for an operator working at odd
hours, alone, at a remote location, and dealing with multiple issue,
which might include: power failures, equipment problems, and
logistical issues. It can be a chaotic situation. Typing long and
complicated passwords in the heat of battle, particularly if they vary
between machines, can be error-prone. Being locked-out will make the
situation more difficult and may increase the amount of data that will
be lost.

If you find that the number of login failures before lock-out is too
small, you can increase it by increasing the value of the `deny`
parameter (`5` in the example below, other typical parameters are
omitted and should not be changed) in:

./etc/pam.d/common-auth
[source]
----
auth required pam_faillock.so deny=5
----

Small integer values (`20` or less) should not be a significant risk
with long and complicated passwords and a unlock time of several
minutes.

==== 5.4.1.4 Ensure inactive password lock is 30 days or less

This is too short for developers/troubleshooters. A value of `60`
would be commensurate with the password reset interval.

:sectnums:

=== Other policies

This subsection describes other policies beyond the CIS benchmark that
may be desirable.

==== TCP wrappers configuration

You may wish to configure TCP wrappers.

===== /etc/hosts.deny

Add:

....
ALL:ALL
....

===== /etc/hosts.allow

Add:

....
sshd:ALL
....

It is recommended that you further restrict _sshd_ to specific hosts
and/or sub-domains.

==== Set log retention period

You may want to set the retention period of system logs by
editing _/etc/logrotate.conf_ and/or _/etc/logrotate.d/*_, as
appropriate.

== CIS Exceptions

:sectnums!:

This section addresses the tests that failed in the CIS benchmark
after all the remediations in this document were applied. The items
are listed by benchmark section numbers.

=== 1.5.2 Ensure bootloader password is set

This must be set later by the system administrator.

=== 2.2.2 Ensure X Window System is not installed

The X11 Window system is required for FS use.

=== 2.2.4 Ensure CUPS is not enabled

The CUPS printing systems is required for operations.

=== 3.5.2.5 Ensure firewall rules exist for all open ports

There is a _ufw_ rule for _Openssh_ (port 22), but the benchmark
doesn't accept that. Additional openings can be added as needed.

=== 3.5.3.7 Ensure nftables service is enabled

Although the benchmark also uses _ufw_, which is enabled and uses
_nftables_, for some reason this is not recognized.

=== 3.5.3.8 Ensure nftables rules are permanent

Although the benchmark also uses _ufw_, which has permanent rules  and
uses _nftables_, for some reason this is not recognized.

=== 4.2.1.5 Ensure rsyslog is configured to send logs to a remote log host

A remote log server must be configured later by the system
administrator.

=== 5.2.6 Ensure SSH X11 forwarding is disabled

Using _ssh_ X11 forwarding is required for for remote FS operations
and testing.

=== 5.3.2 Ensure lockout for failed password attempts is configured

The benchmark, which is for Debian _10_, uses _pam_tally2.so_ for
this. However _pam_tally2.so_ is not available in Debian _11_, having
been replaced with _pam_faillock.so_. The _remediate_ script
implements the intent of the recommended _pam_tally2.so_ configuration
with _pam_faillock.so_.

NOTE: To reset a locked-out user after CIS hardening, as _root_  use
`*faillock --user _username_  --reset*` where `*_username_*` is the
user account. Leave off the `--reset` to see what the current failure
count is.

:sectnums:

== CIS Remediation problems

:sectnums!:

This section details problems with the recommended remediations.  The
items are listed by benchmark section numbers.

Some problems were worked around by adding a boot time _systemd_
service `CISfix` to correct changes that occur on a reboot.

=== 1.1.10 Ensure noexec option set on /var/tmp partition

Enforcing this requirement for the currently running system before all
the other remediations have been applied can interfere with execution
of `apt-get install ...` to install packages needed for the
remediation. Instead, although _/etc/fstab_ is updated in sequence,
remounting the file systm is deferred to the end.

=== 1.4.2 Ensure filesystem integrity is regularly checked

The _/etc/crontab_ entry that should be added is missing the user
(_root_) field.

Debian no longer provides _aide.wrapper_, which is used in the
_/etc/crontab_. A script _/usr/bin/aide.wrapper_ was added that
creates the same _effective_ functionality. The lock file
functionality is not included, but _apparently_ that is no longer
needed, which is _apparently_ why _aide.wrapper_ was not provided by
Debian. The contents of the added script are:

./usr/bin/aide.wrapper
 #!/bin/sh
 #
 /usr/bin/aide "$@"
 RET=$?

=== 1.5.1 Ensure the permissions on the bootloader are configured

The permissions are reset every time _update-grub_ is run, e.g., for a
kernel update. Fixing them was added to the `CISfix` _systemd_
service at boot.

=== 2.2.1.4 Ensure ntp is configured

The remediation makes it less secure. A default policy of `ignore` is
better.

=== 3.3.4 Ensure suspicious packets are logged

The remediation lines added in _/etc/sysctl.d/*_ for this issue are
not respected at boot (unlike all others). To overcome this, the
following lines are used in the `CISfix` _systemd_ service at boot.

....
sysctl -w net.ipv4.conf.all.log_martians=1
sysctl -w net.ipv4.conf.default.log_martians=1
sysctl -w net.ipv4.route.flush=1
....

=== 4.1.5 Ensure events that modify the system's network environment are collected

The 64-bit remediation had the `b64` and the `b32` rules concatenated
on one line.

=== 4.1.16 Ensure kernel module loading and unloading is collected

The 64-bit remediation was missing the `b32` rule.

=== 4.2.3 Ensure permissions on all logfiles are configured

There are two issues:

. The recommended remediation makes the entire directory tree
_/var/log_ unsearchable by everyone except _root_. This breaks some
functionality, in particular email. As a result, the remediation was
scaled back to just the minimum required to pass the test, which was
to just set the permission on the files themselves instead changing
the directory permissions as well. This could be made more targeted.
For example to allow email use, just _/var/log_ and _/var/log/exim4_
could be made searchable.

. The permissions for some logfiles are reset each time the system
reboots. Fixing them was added to the `CISfix` _systemd_ service at
boot.

=== 6.1.6 Ensure permissions on /etc/passwd- are configured

The permissions are reset each time the system reboots. Fixing them
was added to the `CISfix` _systemd_ service at boot.

=== 6.1.7 Ensure permissions on /etc/shadow- are configured

The permissions are reset each time the system reboots. Fixing them
was added to the `CISfix` _systemd_ service at boot.

=== 6.1.8 Ensure permissions on /etc/group- are configured

The permissions are reset each time the system reboots. Fixing them
was added to the `CISfix` _systemd_ service at boot.

=== 6.1.11 Ensure no unowned files or directories exist

After each boot, the file _/var/cache/private/fwupdmgr_ has no owner.
Fixing that was added to the `CISfix` _systemd_ service at boot.

=== 6.1.12 Ensure no ungroup files or directories exist

After each boot, the file _/var/cache/private/fwupdmgr_ has no group.
Fixing that was added to the `CISfix` _systemd_ service at boot.

:sectnums:

[appendix]

== Additional set-up for FS operations

After the CIS hardening is completed, some additional set-up is needed.

=== Fix-ups

There are two issues that may need to be corrected after the CIS
hardening.

. Using the `noexec` option for _/tmp_ causes a problem for the
package management system. The _dpkg-preconfigure_ program places and
executes scripts on _/tmp_ as part of package installation. The
`noexec` option prevents the execution of the scripts. To work around
this issue, you can exeucte:

    cd /root/fsl11/
    ./root_tmp

+

The _root_tmp_ script performs three actions:

.. Creates a one time service at boot to clean the _/root/tmp_ directory
.. Sets _dpkg-preconfigure_ to use _/root/tmp_ for temporary files
.. Creates an initial _/root/tmp_ directory

+

There may be other issues with using the `noexec` option for _/tmp_,
but we don't have any specifics at this time.

. Sometimes the firewall (_ufw_) does not work properly after rebooting.
This has been noticed for remote access to _gromet_ for met. data on
port 50001. There are no other known issues. An apparent fix for this
is to disable and re-enable the firewall. If you have this problem and
the same solution works, a one-time service at start-up can be created
to perform this action:

  cd /root/fsl11
  ./create_ufw_re-enable
+

The new service will run at the next reboot. It is configured to run
_after_ _ufw_ has been started.

=== Enabling user promotion to oper/prog and root

The model used in the FS assumes _oper_ and _prog_ accounts will be
used for operations and programming respectively. However, some
organizations may have security and auditing restrictions that mean
operators must login using their own account (possibly named with
their Agency User ID, or AUID). As the FS currently operates, users
will then need to switch to the _oper_ or _prog_ account after login.
Likewise, if a user is allowed to elevate to _root_, they will need to
do so after logging into their own account. This subsection covers how
to enable this capability. The next subsection <<Adding AUID
accounts>> covers how to add an AUID account. The method described
here, and in the next subsection, uses _dhorsley_ as an example user.

For _oper_ and _prog_, we suggest creating two groups that can _sudo_
to the accounts.

run _visudo_ then add at end:

    %operators      ALL=(oper) NOPASSWD: ALL
    %programmers    ALL=(prog) NOPASSWD: ALL
    %programmers    ALL=(oper) NOPASSWD: ALL

To allow _operators_ to use _rotation_shutdown_, _refresh_secondary_,
_shutdown_, and _reboot_, add (respectively):

   %operators      ALL=(ALL) /usr/local/sbin/rotation_shutdown
   %operators      ALL=(ALL) /usr/local/sbin/refresh_secondary
   %operators      ALL=(ALL) /sbin/shutdown
   %operators      ALL=(ALL) /sbin/reboot

To use these commands the _operators_ will need to enter
(respectively) from their AUID accounts:

   sudo rotation_shutdown
   sudo refresh_secondary
   sudo shutdown
   sudo reboot

A password will be required. Trailing options can be used with the commands, as appropriate.

If the  user can elevate to _root_, also add:

    dhorsley       ALL=(root) ALL

If they don't already exist, create the needed groups:

    addgroup operators
    addgroup programmers

If they don't already, make sure _oper_ and _prog_ have usable shells:

    chsh -s /bin/bash oper
    chsh -s /bin/bash prog

If the accounts haven't been disabled for login already, do so:

    usermod -L desktop
    usermod -L oper
    usermod -L prog

To prevent connecting with _ssh_ using a key, create (or add _oper_
and _prog_ to an existing) `DenyUsers` line in _/etc/ssh/sshd_config_:

NOTE: If you used the CIS _remediate_ script, you should comment out
the line: `DenyGroup rtx` as well.

....
DenyUsers desktop oper prog
....

And restart _sshd_ with:

....
systemctl restart sshd
....

Authorized users can then switch to _oper_ with (similarly for
_prog_ and _root_):

    sudo -i -u oper

No password will be required (except for _root_).

To ensure X authorization works do the following (this example is for
user _oper_ and  works analogously for _prog_ and _root_, but see the
note at the end of step (1) about _root_'s Xresources:

1. Add this to the following file:
+
.~/.profile
[source,bash]
```
if ! [ -z "$XCOOKIE" ]; then
   xauth add $XCOOKIE
fi
if echo $DISPLAY |grep -q localhost; then
#   ssh from remote host with X display
    xrdb -merge ~/.Xresources
else
    if ! [ -z $DISPLAY ]; then
      if xhost|grep -q 'SI:localuser:oper'; then
#       local X display
        xrdb -merge ~/.Xresources
      fi
    else
#     text terminal, do nothing
      :
    fi
fi
```
+
This will also set the Xresources to those of _oper_. (For _root_
    only the first clause would be used since Xresources would not be
    set.)

2. Create the following file
+
./usr/local/bin/oper_account
[source,bash]
```
#!/bin/bash
set -e
if echo $DISPLAY |grep -q localhost; then
 sudo -u oper XCOOKIE="$(xauth list $DISPLAY)" -i
else
 if ! xhost|grep -q 'SI:localuser:oper'; then
   xhost +SI:localuser:oper >/dev/null
 fi
 sudo -u oper -i
fi
```

3. Execute:
+
    chmod a+rx /usr/local/bin/oper_account

The three numbered steps above can be executed for _oper_, _prog_, and _root_
with:

....
~/fsl11/AUID/install_AUID
....

=== Adding AUID accounts

This subsection describes how to add AUID accounts to be used with the
ability to promote to _oper_, _prog_, and _root_ as described in the
previous subsection. As in the previous subsection, the following
method uses _dhorsley_ as an example user.

. Add any needed user accounts as appropriate:

    adduser dhorsley --home /usr2/dhorsley
    chmod 0750 /usr2/dhorsley

+
IMPORTANT: If you are configuring a spare computer, you will need to
make sure the `UID` and `GID` for each user with a home directory on
_/usr2_ is the same on both computers for the system-to-system backup
of _/usr2_ to work properly.
+

[NOTE]
====

For normal operations, AUID users' home directories should be on
_/usr2_. However, for some maintenance accounts, it may make sense to
have the home directory some where else, typically on _/home_. In that
case, use these commands instead:

    adduser dhorsley
    chmod 0750 /home/dhorsley

The step for setting the contents of the home directory below will
need to be adjusted accordingly, see <<note,NOTE>>.

The `UID` and `GID` of the account should still be kept in agreement
between the two computers.

====

. Add each user to these groups as appropriate, e.g.:

+

NOTE: This step assumes that the _operators_ and _programmers_ groups
have been created as described in the previous subsection
<<Enabling user promotion to oper/prog and root>>.

+
    adduser dhorsley operators
+

and/or:

+
    adduser dhorsley programmers

. If the user should be able to manage printers, use:

    adduser dhorsley lpadmin

. If the account will be used by an operator and/or programmer, the X11
environment needs to be set-up. The following command will move an
existing _/usr2/dhorsley_ to _/usr2/dhorsley.FSCOPY_ and create a new
_/usr2/dhorsley_ with a useful skeleton for use with the FS (you will
    be prompted for the account name):

    /usr2/fs/misc/auid_update

+
[NOTE]
====

[[note]]<<note,NOTE>>: If the user's home directory is not on _/usr2_,
but is for example on _/home_, the following commands should be used
instead:

    cd /home
    mv dhorsley dhorsley.FSCOPY
    cd /usr2/fs/st.default/auid
    find . -print|cpio -pmdu /home/dhorsley
    chown -R dhorsley.dhorsley /home/dhorsley
    chmod 0750 /home/dhorsley
====

. Set default desktop

+

To set the correct default desktop (it is remembered per user):

.. Press kbd:[Ctrl+Alt+F1] to get to the GUI login.
.. Enter `*dhorsley*` as the `Username`.
.. Select the "`gear`" icon in the lower right-hand corner.
.. Select `System X11 Default`.
.. Complete logging in with the password.
.. Logout with `exit`.

+

#TODO: Eliminate the need for these steps by implementing a proper
fix, possibly in _fsadapt_.#

=== Setting hostname alias

These steps set a more user friendly alias for the computers of the
form _fs1-<xx>_ and _fs2-<xx>_ where _<xx>_ is the station's two
letter code.  This provides a compact alias for local usage, even for
sites with more than one system, and makes the system identifiable for
remote users in a systematic way. Except as noted below, these steps
should be executed for both the _operational_ and _spare_ computers.


. Edit _/etc/hosts_ and add the new aliases to the appropriate lines.
+
If you have two computers, add the aliases for both to the file on each computer.

. Create a file _/etc/hostname_alias_ that contains the new alias.
.. Execute
+
    cd /etc
    cp hostname hostname_alias
    chmod a+r hostname_alias

.. Edit the new file and change the contents to the new alias.
. Change the system's mailname
+

NOTE: To allow mail to _mailman_ mail lists to work, you may need to
make a use a fake FQDN name, perhaps by appending _.net_ to your
alias, for use in _/etc/mailname_ and
_/etc/exim4/update-exim4.conf.conf_. The two files should be
consistent.

+
.. Edit the file _/etc/mailname_ and change its contents to the new
name, without a domain name unless that is required by remote mail
hosts or mail lists. If so,
<<installation.adoc#_generate_fqdn_in_helo_for_outgoing_mail,Generate FQDN in HELO for outgoing mail>>
in the FSL11 Installation document may also be helpful.

.. Edit _/etc/exim4/update-exim4.conf.conf_, change the value of
`dc_other_hostnames=` to the new alias

.. Execute
+
     update-exim4.conf
     systemctl restart exim4

. Use the new alias in the user prompts and _xterm_ titles for _oper_, _prog_, and all non-system-administrator AUID accounts. In the
`.bashrc` file for each user to be changed:

.. Before the `if` block that sets `PS1` add:

    hostalias_file=/etc/hostname_alias
    if [[ -f "$hostalias_file" ]]; then
        hostalias=$(cat $hostalias_file)
    else
        hostalias=$(hostname)
    fi

.. In the two statements setting `PS1` in the `if` block, change the use of `\h` to `$hostalias`.

.. In the statement setting `PS1` in the `case` block that sets the _xterm_ window title, change the use of `\h` to `$hostalias`.

. For a _spare_ computer only, if you have one:

.. Update _/usr/local/sbin/refresh_spare_usr2_ to use the new alias of
the _operational_ computer in the _ssh_ line.

.. You will need to update the new alias for the _operational_
computer to be recognized as a known host to the _root_ account on the
_spare_ computer. You can do that, as _root_, by using _ssh_ to
`spare@_operational_` where `_operational_` is the new alias for the
_operational_ computer. The command will give you guidance for which
lines need to be deleted in _/root/.ssh/known_hosts_. After deleting
those lines, reconnect using the same _ssh_ command and answer `*yes*`
to confirm connecting. The login will rejected because of the
forced-command setup on the _operational_ computer. The error message
will probably not seem to make sense, but will end with a line like:
`Connection to _operational_ closed.`. Still, the task of recording
the host key will have been accomplished.

=== Installing refresh_spare_usr2 with CIS hardening

This section is useful if you have a _spare_ computer and want it to
have a backup of your _operational_ computer _/usr2_ partition. Using
this method will allow operators to run _refresh_spare_user2_ with
_sudo_. All steps must be performed as _root_ on the specified system.
You should read all of each step or sub-step before following it.

TIP: Read the
<<raid.adoc#_refresh_spare_usr2,refresh_spare_usr2>> section of the
<<raid.adoc#,RAID Notes for FSL11>> document for important information
on the __refresh_spare_usr2__ script.

. On the _operational_ system:

.. _Temporarily_ set _sshd_ to allow _root_ login:

... Edit _/etc/ssh/sshd_config_

+

+

+

Add an uncommented line (or change an existing line) for
`PermitRootLogin` to set it to `yes`

... Restart _sshd_. Execute:

  systemclt restart sshd

.. Create _spare_ account. Execute:

+

----
addgroup spare --gid 2000
adduser spare --uid 2000 --gid 2000
----

+

NOTE: The user's home directory is on _/home_ (by default), not
_/usr2_.

+

+

NOTE: Since the _spare_ account is unique to the _operational_ system,
the UID and GID values of `2000` are chosen to make it easier to keep
the values in sync for other users on both systems. In other words, it
is not necessary to worry about jumping over a low value on the
_spare_ system when values are assigned sequentially, as is the
default. If you think you might have more than 1000 users or groups,
you might want to increase the UID and GID values for the _spare_
account and group.

. On the _spare_ system.

.. Make sure the _operational_ system is represented in the
_/etc/hosts_ file.

+

If it is not already there, add it. It is recommended that it be given
a simple alias for routine use.

.. Install _refresh_spare_usr2_. Execute:

  cd /usr/local/sbin
  cp -a /root/fsl11/RAID/refresh_spare_usr2 refresh_spare_usr2
  chown root.root refresh_spare_usr2
  chmod a+r,u+wx,go-wx refresh_spare_usr2

.. Customize _refresh_spare_usr2_, following the directions in the
comments in the script:

... Comment-out the lines (add leading ``#``s):

+

....
echo "This script must be customized before use.  See script for details."
exit 1
....

... Change the `operational` in the line:

+

....
remote_node=operational
....

+

to the alias (preferred), FQDN, or IP address of your _operational_
system.

... Uncomment the line for CIS hardened systems. The commented out
form is:

+

+

....
#remote_user=spare
....

.. Create and copy a key for _root_. Execute:

+

CAUTION: If _root_ already has a key, you only use the second command
below, to copy it to the _spare_ account.

+

TIP: It is recommended to _not_ set a passphrase.

+

[subs="+quotes"]
----
ssh-keygen
ssh-copy-id spare@_operational_
----

+

where `_operational_` is the alias, name, or IP of your _operational_
system.


.. Enable running the script with _sudo_. Use _visudo_ to add:

+

....
%operators         ALL=(ALL) /usr/local/sbin/refresh_spare_usr2
....

+

+

NOTE: It could be setup for a specific user (but not _oper_ or _prog_
in a CIS hardened system) by replacing `%operators` with the user
account name.

. On the _operational_ system:

.. Set the _spare_ account to only allow a _forced command_ with _ssh_
by replacing the `ssh-rsa` at the start of the first (and only) line of
_~spare/.ssh/authorized_keys_ line with:

+

`command="sudo --preserve-env rrsync -ro /usr2" ssh-rsa`

+

+

+

TIP: If your _spare_ system is registered with DNS, you can provide
some additional security by adding ``from="__node__" `` {nbsp}(note
the trailing space) at the start of the line, where `__node__` is the
FQDN or IP address of the _spare_ system.  It may be necessary to
provide the FQDN, IP address, and/or alias of the _spare_ system in a
comma separated list in place of  `__node__` to get reliable
operation.

.. Enable the _spare_ account to run _rrsync_ with _sudo_ without a
password and with passing environment variables. Use _visudo_ to add:

+

....
spare          ALL=(ALL) NOPASSWD:SETENV: /usr/bin/rrsync
....

.. Lock-out the _spare_ account from normal login (but it must have a
shell). This will disable password login, but not _ssh_ login with
keys, for this account. Execute:


+

----
usermod -L spare
----

.. Disable password aging and inactivity time-out for the _spare_
account. Execute:

+

+

----
chage -I -1 -M 99999 spare
----
