//
// Copyright (c) 2020-2023 NVI, Inc.
//
// This file is part of the FSL11 Linux distribution.
// (see http://github.com/nvi-inc/fsl11).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= FS Linux 11 Installation Guide
J.F.H. Quick, D.E. Horsley, and W.E. Himwich
Version 1.0.1 - April 2023

:sectnums:
:experimental:
:downarrow: &downarrow;

:toc:
<<<
== Introduction

These instructions provide a complete method for system installation
and some tuning. They are not the only method for accomplishing these
goals, but have been well tested. Experts can of course use their own
means, but the farther they deviate from this model, the less support
we will be able to provide.

The standard configuration uses a RAID1 system with removable disks.
Normally, two disks would be in use at a given time. A third disk is
used as a back-up and rotated into use periodically. More disks can be
used for further redundancy. You can of course provide your own
back-up method and can install the system to a single disk if you do
not want to use the software RAID.

If you are using the RAID configuration, you may wish to review the
<<raid.adoc#_recommended_practices,Recommended practices>> subsection
of the <<raid.adoc#,RAID notes for FSL11>> document before installing.
However, all of the practices listed there can be implemented after
the installation steps below are complete.

TIP: Removable disks should be used with a carrier/receiver system
that can tolerate a large number of insertions; "`bare`" disks should
not be inserted repetitively. Two receivers would normally be mounted
in the computer chassis. Each disk would be in its own carrier. We can
provide a recommendation for a carrier/receiver system if you need
one.

Please note that for each step in this guide, we recommend you
carefully read all the included caveats and notes as the material is
not always logically sequential, i.e., instructions may proceed
explanations that impact what you actually type.

.FSL distributions
|=============================================================
| FS Linux |Release Name|Debian Version| Linux kernel | Year

|   _1_    |            | (Slackware)  | _1.2.<x>_  | 1994
|   _2_    | _bo_         |     _1.3.1_    | _2.0.29_ | 1997
|   _3_    | _hamm_       |     _2.0_      | _2.0.34_ | 1998
|          | _slink_      |     _2.1_      | _2.0.36_ | 1999
|   _4_    | _potato_     |     _2.2_      | _2.2.18_ | 2000
|   _5_    | _woody_      |     _3.0_      | _2.2.20_/_2.4.18_ | 2002
|   _6_    | _sarge_      |     _3.1_      | _2.4.27_ | 2005
|   _7_    | _etch_       |     _4.0_      | _2.6.18_ | 2007
|   _8_    | _lenny_      |     _5.0_      | _2.6.26_ | 2009
|          | _squeeze_    |     _6.0_      | _2.6.32_ |
|   _9_    | _wheezy_     |     _7.0_      | _3.2.0_  | 2014
|          | _jessie_     |     _8.0_      | _3.16.0_ |
|  _10_    | _stretch_    |     _9.0_      | _4.9.0_  | 2020
|          | _buster_     |    _10.0_      | _4.19.0_ |
|  _11_    | _bullseye_  |     _11.0_      | _5.10.0_ | 2023
|=============================================================

The FSL11 documents follow the FS font conventions, which can be found
at: https://nvi-inc.github.io/fs/misc/font_conventions.html.

== Choosing architecture and creating installation media

FSL11 can be configured for either the _i386_ or _amd64_
architectures. With FSL11 it is necessary to use Field System version
_10.2_ or later. Those FS versions support both architectures
natively, so either may be used. The _amd64_ architecture is preferred
and should be used if possible (it should be unless the processor is
very old, from about 2010 or older). However, some work may be
required to port your station code from a 32-bit to a 64-bit OS. An
automatic tool has been developed to help with this, and can be
provided upon request. Usually the _i386_ architecture will work on
any processor, but requires use of the `Legacy` (or `BIOS`) boot mode
in most cases. The _amd64_ installation media will fail to boot on a
system that is 32-bit only.

To install Debian _11_, you can either use a DVD or USB drive. The latter is
faster, and also easier if you wish to use UEFI. Directions for creating your
installation media can be found online. 

NOTE: Don't be confused by the _amd64_ name, this architecture supports both
AMD and Intel manufactured x86-64 processors. This includes CPU lines such as
Ryzen, Epyc, Core, and Xeon. The naming scheme dates back to when Intel had a
competing and incompatible 64-bit architecture _ia64_.

You can install from a DVD drive, USB device, or over the network. Any revision of
_11.<x>_ installer should work fine.
Note also that installing from DVDs as described here is
recommended mainly for sites with little to poor Internet connectivity (even
then, use of a single DVD may suffice) and the equivalent use of a "`Debian
GNU/Linux _11.<x>_ Bullseye - Official _i386_/_amd64_ netinst CD`" would suffice for
installation at most sites with good connectivity. Official images for the installer
can be found at: https://cdimage.debian.org/cdimage/release/ or alternatively,
should your hardware require non-free firmware, unofficial images for the
installer that also include all available non-free firmware can be found at:
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/

The details of creating your installation media can be found in the Debian
installation guide available from:
https://www.debian.org/releases/bullseye/installmanual


== Motherboard setup

CAUTION: If you are installing to a virtual machine, make sure it is
configured to have at least two cores. This is required for FS display
server support.

[NOTE]
====

Some hardware may require special procedures. For cases we know about,
instructions are provided in top-level sub-directories of the
repository, which is visible at https://github.com/nvi-inc/fsl11. In
addition to special instructions, there may be needed software/drivers
in the sub-directories. The following table lists the cases that are
currently covered. Some of these solutions may be useful for other
hardware with the same issues. If you have the listed hardware or
issue, we recommend reading the instructions before beginning the
installation.

.Special installation instructions available
[cols="1,3,3"]
|=============================================================
| Directory | Hardware |Issue

| | | None at this time
|=============================================================

====
Modern motherboards offer two forms of booting: native UEFI or BIOS
emulation ("`Legacy`"). UEFI is the preferred approach.  Either mode of
boot is supported by this installation guide, and you will be given
alternatives when the instructions differ. 

Decide which boot mode you want to use and select it through the
motherboard _setup_ menu (typically by pressing kbd:[Delete] during
the power-on self test, aka POST).

Make sure that the motherboard time is set to the current Coordinated
Universal Time, i.e., UTC, and the motherboard can boot from the
installation media.

While you are in the motherboard menu, make sure that hot-swapping is
enabled for the controllers of both the _primary_ and _secondary_
disks. This is necessary for disk rotation and recoverable testing.

TIP: For UEFI, some motherboards may switch to booting to the UEFI
shell if they fail to find a hard disk that will boot. This might
happen, for example, if you attempt to boot from a blank disk. If you
become stuck booting to the UEFI shell, you may need to enter the
motherboard's _setup_ utility to restore booting from the hard disks.
The `Boot` menu may be where this is set. You may be able to disable
use of the UEFI Shell, which may eliminate this situation.

== First stage installation

This guide assumes that you have only one disk installed in the
machine initially even if you intend to use a RAID configuration. Use
of a single disk (for a test install, etc.) is also annotated below.

NOTE: The single dish install approach is used because it is faster
than a dual disk install. It also allows you to control when the
syncing for the second disk occurs, such as when you leave for the
evening. The setup of a second and third disk is covered in the
<<Setup additional disks>> subsection below.

. Install your smallest disk in the _primary_ slot (the one connected
to the lowest numbered SATA controller, usually `0`.

+

CAUTION: For the RAID to work seamlessly with other disks later, you
must make sure that the smallest disk of the ones available is used
for the installation.

=== Boot from the installation medium

. Connect an active network cable to your lowest numbered interface
(only). Usually it is on the left if there are two.

. Insert/plug-in your installation media and reboot.

+

To boot from the installation media you may need to bring up your
motherboard's _setup_ utility, which is typically accessed by pressing
kbd:[Delete] during the POST. From there you may need to access a menu
such as `Save{nbsp}&{nbsp}Exit` (or `Boot`), to select overriding to
boot with the installation media.

+

TIP: If the system was most recently booted from a hard disk, you may
need to boot one time with no hard disk installed for the
motherboard's _setup_ utility to recognize the USB drive as a valid
boot override option. If the _setup_ utility does not recognize the
USB drive at all, it may be necessary to turn the power off, remove
the USB drive, reinsert it, and then reboot. Making the USB the first
boot device _temporarily_ may be necessary.

=== Set boot options and boot installer

At the `Installer boot menu`:

. _Highlight_ `Install` (or `Graphical install` -- only the installer
  interface differs -- but this may not work on some video hardware)
+
* UEFI: press kbd:[e], then kbd:[{downarrow}] three times (`vmlinuz`), then kbd:[End]
// The above does not work for asciidoctor-pdf for PDF, use this instead:
//    * UEFI: press kbd:[e], then the `downarrow` three times (`vmlinuz`), then kbd:[End]
+
NOTE: If kbd:[e] doesn't work, UEFI is not available.  It may be possible to enable it in the BIOS.
+
* BIOS: press kbd:[Tab] 
. To the end of the displayed command, add the additional options:
+
   locale=en_US.UTF8 netcfg/disable_dhcp=true time/zone=UTC
+
NOTE: Whilst typing a `/` (slash) it may automatically be changed (escaped) to
      `\/` (i.e. preceded by a backslash). This is normal behaviour and harmless.

. Press:
+
    * UEFI: kbd:[F10] 
+
    * BIOS: kbd:[Enter]

NOTE: You may omit the `netcfg/disable_dhcp=true` if you want to use DHCP to
configure the network settings of this machine, though this is not advised.

NOTE: You can additionally use `partman-partitioning/default_label=gpt` if you wish
to force the use of a GPT partition table on a disk that is smaller than 2 GB,
but beware - some older BIOS versions cannot handle GPT formatted disks.

NOTE: If you do not set a locale or set `locale=C`, you will be
prompted to select your language and your country. However some
applications may have problems if a UTF8 locale is not used.

The installer will now boot.

=== Select a keyboard layout

Find your keyboard on the `Keymap` list, highlight it, and press
kbd:[Enter]. (The most common one is `American English`)

The installation media is now scanned and additional installer
components loaded.

=== If you are presented with a dialog asking for non-free firmware files

You may need to locate the files requested (especially if they relate
to your network or disk-drive interfaces) and place them on a USB
stick which should be inserted at this stage. If you do have the
required files select `Yes`, otherwise press kbd:[Tab] to select `No`
then press kbd:[Enter] to continue. It may well be simpler just to use
the unofficial installer images mentioned above that include all
available non-free firmware.

=== Configure the network

. If you are presented with a dialog asking which interface to use as
`primary`

+

This is typically only shown if two or more network interfaces are found,
which might include a virtual FireWire interface in some cases.
Select the interface you require (usually `eno1`) and press
kbd:[Enter].

Unless you are using DHCP (which is not advisable) you will be
prompted to:

[start=2]
. Type in the required static IP address in the form `_xxx.xxx.xxx.xxx_`
(where each `_xxx_` is any integer from 0 - 255 inclusive) and press
kbd:[Enter].

. Type in the required netmask in the form `255.__yyy.yyy.yyy__` (where each
`_yyy_` is typically 0, 64, 128, 192 or 255) and press kbd:[Enter].

. Type in the required gateway IP address in the form
`_xxx.xxx.xxx.xxx_` (where each `_xxx_` is any integer from 0 - 255 inclusive)
and press kbd:[Enter].

. Type in the required nameserver IP addresses, space separated, in
the form `_xxx.xxx.xxx.xxx_` (where each `_xxx_` is any integer from 0 - 255
inclusive) and press kbd:[Enter].

=== Set a hostname
Backspace over the default hostname _debian_ and type in the name
you require (if not already retrieved via DNS), then press  kbd:[Enter].
Enter the required Internet Domain name (if not found) and press  kbd:[Enter].

=== Enter a suitable root password

Twice as prompted.

=== Setup first account

Enter `*Desktop User*` for the name of the new user
then press  kbd:[Enter]  to accept _desktop_ as the username and enter a (real)
password twice as prompted.

=== Get network time

The installer now tries to set the time using NTP. If this is not
possible at your site due to your firewall etc., you may need to press
kbd:[Enter] to cancel this process.

=== Partition the disk

NOTE: If you are using UEFI and the disk was previously used for BIOS, you may need
to confirm forcing UEFI installation.

. When prompted for a partitioning method, select `Manual`

==== Setup physical partitions

. Create a new partition table by:

.. Select your disk, something like `SCSI1 (0,0,0) (sda) - 4 TB ATA
SATA HARDDISK`, and press kbd:[Enter].

+

+

WARNING: Do _not_ select your installation media.

.. The installer may warn: `You have selected an entire device to
partition…`. If so, select `Yes`. If you are prompted to delete RAID
partitions, select `Yes`.

. Select the (one and only entry) `FREE SPACE` under your disk. There
should be no RAID or LVM partitions shown.

+

+

[NOTE]
====

If other entries and/or RAID or LVM partitions are shown, you will
need to delete them before proceeding.

If no RAID and/or LVM partitions are shown, a possible solution may be
to delete individual partitions until you have a single entry, `FREE
SPACE`.

If that doesn't work or RAID and/or LVM partitions are shown, you may
be able to use `Guided partitioning` to delete the existing
configuration (and temporarily create new partitions). In this case,
select `Guided partitioning`, then select `Guided - use entire disk`.
Then select your disk, such as listed above, do _not_ select a RAID or
your installation media device. Then select `All files in one
partition (recommended for new users)`. You may be prompted to confirm
deleting RAID partitions and/or removing logical volume data, which
you must do to continue. Then you should be able to continue with
selecting your disk, as above.

If the `Guided partitioning` method above doesn't work or you have
problems later creating the RAID or LVM partitions, then other means
will be needed. There may be more complicated paths through the
partitioner that will work or, perhaps easier, you may need to
overwrite the start of the disk with a large number, say 2 GiB (but
possibly more, if that doesn't solve the problem), of zeros.

<<zeros,Overwriting with zeros>>[[zeros]]: can be implemented (for 2
GiB) at this stage in the installer with:

. Press kbd:[Ctrl+Alt+F2] to switch to a different console.

. Press kbd:[Enter] to activate the console.

. Execute:

 dd if=/dev/zero of=/dev/sda bs=1G count=2
 sync;sync
 reboot

. When the system reboots, restart the installation.

====

. Select `Create a new partition`

.  Then for
** UEFI:  Enter `*1GB*` in the size, then select `Beginning` of the disk.
** BIOS: Enter `*1MB*` in the size, choose `Primary` (rather than `Logical`) if asked for the partition type, then select `Beginning` of the disk.

. Then for
** UEFI: Select `Use as` then select `EFI System Partition`
** BIOS: Select `Use as` then select `Reserved BIOS boot area`, or alternatively `do not use the partition` if the former option is not available.

. Now select `Done setting up the partition`.

. Next select the `FREE SPACE` and `Create a new partition` again.
+
NOTE: You may see a small `1MB FREE SPACE` at the start of the disk. This is
fine, just be sure to choose the large `FREE SPACE` at the end of the disk.

. This time choose the whole amount of free space (the default) and choose `Primary` for the partition type if asked.

. Select `Use as`, then select `physical volume for RAID`, then `Done
setting up the partition`

+

NOTE: If you physically only have one disk bay and wish to construct a FSL11 `test-bed`,
it is possible to avoid using the software RAID layer entirely. Simply select `Use as`, then select `physical volume for LVM`
for this partition instead and skip ahead to <<Setup Logical Volume Manager (LVM)>> below.
However, please note that a single disk setup is not recommended for any _operational_ system.

==== Setup RAID

. Select `Configure software RAID`. Then select `Yes` to write the
  changes to the disk.

. Select `Create MD device`, choose `RAID1` and use `*2*` as the
number of devices and `*0*` as the number of spares.

. Despite the fact that the instructions say you must select exactly
two partitions, select only one. Select the RAID partition you just
created by pressing kbd:[Space]. This should be _/dev/sda2_. Then
press kbd:[Enter] to continue. Select `yes` if prompted to write
changes to the disk.

+

NOTE: If the newly created RAID partition doesn't appear as an option,
you may need to use the method of <<zeros,Overwriting with zeros>> in
the <<Setup physical partitions>> step above.

. Select `Finish`.

. Back in partitioning, select the partition `#1` (with no designated use) _under_
`RAID1 device #0` and press kbd:[Enter]

+

NOTE: If that partition appears immediately after being created
already having a designated use, perhaps `lvm`, you may need to use
the method of <<zeros,Overwriting with zeros>> in the
<<Setup physical partitions>> sub-step above.

. Select `Use as`, then select `physical volume for LVM`, then `Done
setting up the partition`

==== Setup Logical Volume Manager (LVM)

. Now choose `Configure the Logical Volume Manager` and select `Yes`
if prompted to write the changes to the disk and keep the current
layout and configure LVM.


. Choose `Create volume group`
. Enter a name appropriate for the machine and group, e.g., `*vg0*`, and press kbd:[Enter]
. Select the raid device _md0_ (or _sda2_ if not using RAID)  by pressing kbd:[Space], then press kbd:[Enter]
to continue

. For each item in the following table run `Create logical volume`,
select your volume group and assign the corresponding name. Those
marked with `*` are optional unless you are applying CIS hardening.

+
.Logical volumes
|=======================================
|  |Mount point    | LV name | Size

|1 |_/var/log/audit_ | `audit` *   | 4 G
|2 |_/boot_          | `boot`     | 1 G
|3 |_/home_          | `home`     | 4 G
|4 |_/var/log_       | `log` *     | 4 G
|5 |_/_              | `root`     | 50 G
|6 |(swap)           | `swap`     | 8 G
|7 |_/tmp_           | `tmp`      | 50 G
|8 |_/var_           | `var` *     | 8 G
|9 |_/var/tmp_       | `vartmp` *  | 8 G
|10|_/usr2_          | `usr2`     | remaining disk space _less ~100 GB_
|=======================================

. In the LVM configuration window, select `Finish`

. Then for each logical volume in the table except `swap`, do the following:
.. Select the partition (e.g., `#1`) for each `LV name` (and press kbd:[Enter])
.. Select `Use as` and press kbd:[Enter] then select `Ext4 journaling file system`
.. Select `Mount point`, press kbd:[Enter], then select the appropriate mount point from the list or use `Enter manually` if not there.
.. Select `Done setting up this partition`

. For the `swap` logical volume, select `Use as` then select `swap area`, followed by `Done setting up this partition`

. Back in the partition screen, select `Finish partitioning and write changes to
the disk` and select `Yes` to write the changes. For big disks, it may take
a little time to create the `ext4` file systems.

The Debian base system is now installed from the installation media, which
usually only takes a few minutes.

=== Configure the package manager

If you started from a _netinst_ CD image, the installer now assumes
you will install only from the network, and jumps straight to the
<<archive,`Choose your Debian archive mirror country`>> part of the
dialogue as detailed below.

If you are using DVD installer you will be prompted to scan additional DVDs.
Scanning the additional DVDs (and obtaining copies of them in the
first place) is entirely optional, and is only useful if you don't have a
reliable network connection to a suitable Debian mirror and hence would
prefer not to download packages you could get from the DVD.

NOTE: If you do want to use a mirror in the future, it is better not
to scan any DVDs at this stage and to scan them later during Stage 2
using _apt-cdrom_.

For each additional DVD you wish to scan, insert it in the drive, select
`Yes` and press  kbd:[Enter]  to perform the scan (which takes a while.)

(If you are using DVDs, and are prompted to insert another DVD, you
will need to use `*eject /dev/cdrom*` from another virtual console to do this)

Select `No` and press  kbd:[Enter]  to continue once you are done.
If prompted, insert the "`Debian GNU/Linux _11.<x>_ Bullseye - Official _i386_/_amd64_
Binary-1 DVD`" back into the DVD-ROM drive and press  kbd:[Enter].

WARNING: If you do scan additional DVDs, the following useful dialogue
which allows you to select a suitable network mirror from a country-based
list may be suppressed.

Select `Yes` and press  kbd:[Enter]  to use a network mirror (unless you
have inadequate Internet access - but then you must scan all DVDs.)

<<archive,`Choose your Debian archive mirror country`>>[[archive]]:
Select from the list if available and press kbd:[Enter]. (If your
country is not available choose the country nearest to you in a
network connectivity sense.)

Select the fastest Debian mirror from those available.

TIP: The new `deb.debian.org` mirror is a good choice for most
sites as it uses DNS to find a local mirror.

Enter any necessary `HTTP` proxy information (usually left blank).

Software is downloaded briefly.

=== Do not participate in popularity-contest

When prompted to join the popularity-contest, select `No` and press kbd:[Enter]

=== Choose your packages

When prompted to choose packages, select `SSH server` by moving to
that row with the arrow keys and pressing kbd:[Space] on it (unless
you don't want it).

TIP: If you have a small disks and are worried about space, then you can
also press kbd:[Space] on `Desktop Environment` to unselect it (which may
then change the dialogue presented below).

Finally press, kbd:[Enter] to install the standard system.

The Debian standard system is now installed from the installation media plus any
updates from the network mirror and/or _security.debian.org_ site if they can be
reached. 

This can take a while, up to one and a half hours or more.


=== Install the GRUB bootloader (BIOS boot only)

NOTE: With UEFI boot, you will not be presented with this option; GRUB will automatically be
installed to the first ESP partition.

At `Install GRUB to Master Boot Record` select `yes` then select _/dev/sda_

When prompted, press kbd:[Enter] to install to the master boot record.

=== Disable Wayland (optional)

This step should only be needed if your CPU does not include a GPU and
you do not have an add-on graphics card. In that case, you are using
the motherboard graphics support. Disabling `Wayland` is known
specifically to be necessary for the `X11SCA-F` motherboard, which
uses the `AST2500` graphics chip. If you don't know that you need to
disable `Wayland`, we recommend that you initially leave it enabled.
Whether your choice works or not should be evident when you start the
<<Second stage installation>> step below. The console may be very
difficult, even impossible, to work with. In that case, please see the
<<wayland_recovery,Wayland recovery>> *NOTE* below.

To disable `Wayland`:

TIP: These instructions step can be executed when the installation
stops for input in the next step, <<Remove installation media>>.

. Press kbd:[Ctrl+Alt+F2] to switch to a different console.

. Press kbd:[Enter] to activate the console.

. Edit _/target/etc/gdm3/daemon.config_, uncomment `Wayland=False`,
and save the file.

+

The only editor available at this point may be _nano_.

. Execute:

 sync;sync
 exit

. Press kbd:[Ctrl+Alt+F1] to return to the Installer dialog.

[NOTE]
====

<<wayland_recovery,Wayland recovery>>[[wayland_recovery]]: If you find
you have made the wrong choice, there are at least three possible ways
to recover:

. If the console is marginally usable, you may be able to login on a
text console to adjust the contents of _/etc/gdm3/daemon.config_ as
needed, then execute:

 systemctl restart gmd3

. Use the procedure in the <<Rescue Mode>> appendix and adjust the
contents of _/etc/gdm3/daemon.config_ as needed.

. Reinstall from scratch and make the opposite choice.

====

=== Remove installation media 

Remove the DVD from the DVD-ROM drive (it should be auto-ejected), or
unplug the USB drive, and press  kbd:[Enter]  to reboot into the newly
installed system.

TIP: It would generally be wise to disable booting from DVD-ROM and
floppy i.e., anything other than the hard drive, in the BIOS just in
case someone leaves something nasty in the machine's removable drives
by mistake.

== Second stage installation

You should now have booted to your new OS.

=== Login as root 

TIP: Versions before Debian 9 ran X11 on virtual console 7. As of
Debian 9, the graphical environment login is on virtual console 1.
Each login there for a different user creates a session on the next
unused virtual console.

Switch to Virtual Console 2, by pressing kbd:[Ctrl+Alt+F2].

Enter _root_ and press kbd:[Enter], then enter the _root_ password you set
earlier.


=== Remove the dummy Desktop User (optional)

Unless you want an account that is set up to use the default desktop
environment, delete the _desktop_ user with:

   deluser --remove-home desktop

NOTE: If you do keep this account, you will not be able to run the FS from
it unless you add this account into the additional hardware access groups
such as is done for _oper_ and _prog_ by _fsadapt_.


=== Setup HTTP proxy for APT (optional)

Should you wish to make APT use an HTTP proxy for downloads,
create the new file _/etc/apt/apt.conf.d/00proxies_ using _vi_ containing:

   ACQUIRE::http::Proxy "http://proxy.some.where:8080/"; 

to use a proxy _proxy.some.where_ at port `8080` for example.

=== Edit /etc/apt/sources.list

Using your favourite text editor, eg _vi_, and comment out all `cdrom`
entries (unless you don't have a decent Internet connection and need
to use DVDs, whereupon the dialogue presented below may differ) and
check you have the equivalent of the following entries towards the top
of the file, adding in `contrib` and/or `non-free` as needed:

   deb http://deb.debian.org/debian/ bullseye main contrib non-free
   deb-src http://deb.debian.org/debian/ bullseye main contrib non-free

and likewise the equivalent of the following entries towards the
bottom of the file, again adding in `contrib` and/or `non-free` as
needed:

   deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
   deb-src http://deb.debian.org/debian/ bullseye-updates main contrib non-free

(where you can use any suitable mirror instead of _deb.debian.org_)

Also add `contrib` and/or `non-free` to the lines referring to the
_security.debian.org_ mirror in the middle of the file.

WARNING: you _MUST_ use `bullseye` and _NOT_ `stable` for the
distribution in all these entries (but CD/DVD entries might use
`unstable`.)

=== Update APT's list of packages

TIP: Recent versions of Debian have the _apt_ program, which gives a more
     user-friendly interface to the package manager than _apt-get_. We
     generally use _apt-get_ except for applying updates.

Next tell APT to update its internal source list of packages using

   apt-get update 

NOTE: It is also possible to add additional DVDs at this stage using the
`*apt-cdrom add*` command.

=== Download the FS Linux 11 package selections

. Install _git_ and _dselect_
+
   apt-get install git dselect

. Update _dselect_'s package lists

   dselect update

. Get the selections by downloading this repository:
+
    cd /root
    git clone https://github.com/nvi-inc/fsl11
    cd fsl11

. Feed the package selections into _dpkg_ using the command, for _amd64_

   dpkg --set-selections < selections/fsl11_amd64.selections

+

or, for _i386_

   dpkg --set-selections < selections/fsl11_i386.selections


. Start the additional package installation with

+

    apt-get dselect-upgrade

+

then press kbd:[Enter] to confirm any updating of installed packages
(where you have an Internet connection) and the installation of
currently ~191 new packages (downloading ~185 MB from the Internet
and/or DVDs) for _amd64_ with UEFI -- probably different for _i386_
and/or BIOS -- unless you did not select the Desktop or added other
tasks earlier.

+

Downloading commences for up to half an hour (depending on your Internet
access and the exact revision of DVDs used).

+

Installation runs to completion.


=== Clean up the APT download directory

So that the update mechanism will work correctly, run

   apt-get clean


== Third stage installation

=== fsadapt

In the _/root/fsl11_ directory, start _fsadapt_ with

    ./fsadapt

==== FS Adaptation: Modifications (Window 1)

Using the arrow keys and kbd:[Space] make your selections and press kbd:[Enter].

* If you are not using a GPIB board or USB dongle, you can deselect
the GPIB option.

* If you are using the RAID configuration, you must _not_ deselect
the `mdinc` option.

==== FS Adaptation: Setup (Window 2)

All of the steps in Window 2 need to be done once (even if you do not
intend to use the serial ports) with the exception of `sshkeys` which
can be used to generate new SSH keys if required.
If you did not select the GPIB option in the previous page deselect the
two related options on this page (but do not deselect `set_perms` as it
is always required). Otherwise, simply press kbd:[Enter] with the `OK`
selected to continue.

NOTE: The `updates` option relies on email to _root_ being re-directed
to some mailbox that will be read regularly, so make sure you set that
up and test it as well (see the <<Configure e-mail>> section in the
<<Additional Setup Items>> appendix). The installer sets it up to go
the _desktop_ account by default which would definitely be a problem
if you have removed that!

==== GPIB driver configuration (optional)

On the `/etc/gpib.conf` screen, use the up/down arrow keys to select the
required GPIB controller and press kbd:[Enter] on `OK` to continue.

==== Serial port configuration

On the `/etc/default/grub: serial port configuration` screen
up/down arrow keys to select the required RS232 serial card
(or `None` if you don't have one) and press kbd:[Enter] on `OK`
to continue.

==== FS Adaptation: Settings (Window 3)

On Window 3 you can choose to modify the email or network settings if required.
Simply press kbd:[Enter] on `OK` to continue.

==== FS Adaptation: Network Services (Window 4)

The Window 4 will show what services are enabled.  Use the up/down
arrows and kbd:[Space] to select `secure` and press kbd:[Enter] on
`OK`.  Thereafter use the up/down arrows and kbd:[Space] to select
those services you actually need.  If you need printing, you will need
to select `netipp` (remote access to this can be blocked by
    configuring _ufw_ with either not explicitly allowing or instead
    denying the CUPS service).  Press kbd:[Enter] on `OK` to set them
up and finish with _fsadapt_.

Note that the _fsadapt_ script can be re-run at a later date should you need to
change the adaptations.

=== Set passwords

Set passwords for the _oper_ and _prog_ accounts with:

   passwd oper
   passwd prog

entering the passwords twice as prompted.

=== Install tools for RAID (optional)

You can install some useful tools for working with the RAID, if you're actually using it, with:

   ~/fsl11/RAID/install_tools

The rest of this document assumes the first three of these tools have
been installed. The six tools are:

* _mdstat_ -- for all users -- check on the RAID status

* _refresh_secondary_ -- for _root_ -- refresh a _secondary_ disk that
is from the same RAID

* _blank_secondary_ -- for _root_ -- initialize a _secondary_ disk,
must be used with extreme care

* _rotation_shutdown_ -- for _root_ -- shutdown the system _if_ it is
safe to rotate disks

* _drop_primary_ -- for _root_ -- deliberately drop the _primary_ disk
out of the RAID for use as a backup

* _recover_raid_ -- for _root_ -- re-add a disk that fell out of (or
was removed from) the RAID back into it

TIP: More information about RAID operation can be found in the
<<raid.adoc#,RAID notes for FSL11>> document.

=== Download the Field System

[subs="+quotes"]
....
 cd /usr2
 git clone https://github.com/nvi-inc/fs fs-git
 cd /usr2/fs-git
 git checkout -q _tag_
....

where `_tag_` is the latest available release, _10.2.0_ or later.

[TIP]
====

At the time of this writing, _10.2.0_ has not been officially
released. The `_tag_` for the latest alpha version is currently
_10.2.0-alpha2_. That, or a later tagged alpha version or beta
pre-release, should suffice for an initial installation. However they
should not be used for operations. You should update to _10.2.0_ as
soon as it is available. If _10.2.0_ has not been officially released,
you should ignore the *IMPORTANT* block immediately below.

You can find the most recent beta release of _10.2_ at:

https://github.com/nvi-inc/fs/releases

If none are available, you can find the most recent tagged alpha
version of _10.2_ at:

https://github.com/nvi-inc/fs/tags

====

[IMPORTANT]
====

You should install the latest official release. To find it, go to:

https://github.com/nvi-inc/fs/releases

You should probably use the most recent _feature_ release (ending in
_.0_ with no trailing _-<string>_, e.g., _10.2.0_. However, if there
is a more recent _patch_ release (not ending _.0_) for the most recent
feature release, you should use the most recent patch release. For
example, if _10.2.0_ is the most recent feature release and there are
corresponding patch releases, _10.2.1_ and _10.2.2_, then the last
one, ending _.2_, is probably the best choice.

====

=== Run FS install script

This will set the _/usr2/fs_ link, set _/usr2/fs-git permissions_, and
install default copies of all the FS related directories.

   make install

and enter `*y*` to confirm installation.

=== Make the FS

The FS must always be compiled as _prog_.

WARNING: Make sure you log-out as _root_, and log-in again as _prog_.

   cd /usr2/fs
   make >& /dev/null

then

    make -s

to confirm that everything compiled correctly (no news is good news).

=== Reboot the new system

Remove any DVD from the machine and restart the machine using
_reboot_ as _root_ or kbd:[Ctrl+Alt+Del] whilst watching that
everything starts up smoothly.

== Fourth stage Installation

=== Setup additional disks

If your are using a RAID, follow the steps in this subsection to setup
the second and third disks.

NOTE: Additional disks should be at least as large as the disk already
in use.

NOTE: You will need to have hot-swapping enabled in your motherboard's
setup menu, at least for the controller for the _secondary_ disk (it
should also be enabled for the _primary_).

NOTE: This subsection assumes you have installed the RAID tools
according to the <<Install tools for RAID (optional)>> subsection
above.

. If you have a second disk (_secondary_) in the RAID:

.. Shut the system down with the _rotation_shutdown_ command.

+

+

This command will check the status of the RAID and proceed to shutting
down _only_ if the RAID is synced. There are three errors that can
prevent shutting down: (i) if the FS is running, you should terminate
it before trying again; (ii) if the RAID is `recovering`, you will
need to wait until the recovery is finished before shutting down, you
can check the progress with the _mdstat_ command; and (iii) if the
RAID is `degraded`, seek expert advice.

.. Remove the disk in the _primary_ slot and place it on the shelf,
labelled appropriately as the _shelf_ disk for this system with the
date.

.. Move the disk in the _secondary_ slot to the _primary_ slot.

. Initialize the new disk

+

IMPORTANT: Do not initialize a disk unless you are sure there is no
data on it that you need to preserve.

+

For the first time use of an additional disk with a new install, the
disk should be initialized to make sure it has no existing structure.
This should be done even if the disk has been used in a different FS
computer or a previous install on this computer.

.. Boot with just the _primary_ disk installed.

+

TIP: If your system is already running with no second disk
(_secondary_) installed, you can skip rebooting.

.. Use the script:

   blank_secondary

+

+

The script will wait for the new disk to be turned on. Insert a new
disk in the _secondary_ slot. The secondary slot is the one connected
to second lowest numbered SATA controller, usually `1`. Turn the key
to turn the disk on. There will be a prompt asking if wish to proceed.
If it is a new disk or you are sure it safe to erase this disk, answer
`*y*`. If you are unsure about this or otherwise need to abort, answer
`*n*`.

. Refresh the now blank _secondary_ disk

+

Run the script:

    refresh_secondary

+

Once you reach the message that you can check on the recovery with
_mdstat_ , you can resume using the computer as usual. You can safely
reboot at this point, if it is needed; just don't remove either disk
until the recovery is finished.

+

You can check the progress of the recovery with:

    mdstat

+

When the recovery is complete, you can repeat the process of this
entire subsection, <<Setup additional disks>>, to initialize another
disk.

== Post install

The FS on your newly installed system should now be ready to be
customized for your site's requirements by tailoring the control files
in _/usr2/control_ and adding suitable station specific software to
_/usr2/st_. See the files in the _/usr2/fs/st.default/st-0.0.0_
directory for starter versions of the latter.

Please refer to the appendix <<Additional Setup Items>> for OS
customizations that you may find useful.

[appendix]
:sectnumlevels: 4

== Additional Setup Items

This appendix covers several customizations that may be helpful
depending on the requirements for a system. It serves as a reference
for how to make these changes, but can also be helpful as a checklist
when setting up a new system. All actions in this section require
_root_ permissions.

=== Additional security and CIS Benchmarks

For stations that wish to conform to the additional security
recommendations of the Center for Internet Security (CIS), move on to
the <<cis-setup.adoc#,CIS hardening FSL11>> document.

==== Alternate hardening

If you don't want the complete CIS hardening, which creates some
inconveniences and is only required in certain environments, you may
still be interested in applying a subset of the remediations. You can
pick and choose those from the <<cis-setup.adoc#,CIS hardening FSL11>>
document and its script.

A useful minimum set of features to apply would be to install _ufw_
and block everything except _ssh_ and further restrict _ssh_ access with
TCP Wrappers.

===== ufw setup

To install and configure _ufw_ to only allow _ssh_ for incoming
connections, use the commands:

....
apt-get -y install ufw
ufw allow OpenSSH
ufw --force enable
....

Addition setup for _ufw_ is covered below in the
<<More firewall rules>> subsection.

===== TCP Wrappers setup

A base setup for TCP Wrappers is

./etc/hosts.deny
----
ALL:ALL
----

./etc/hosts.allow
----
sshd:ALL
----

It is recommend that you further restrict _sshd_ by using specific
hosts and/or sub-domains instead of `ALL`. Please use
`*man{nbsp}hosts_access*` for more information about configuring TCP
Wrappers

===== More firewall rules

The following tersely summarizes some _ufw_ settings that may be
useful:

....
#SSH
ufw allow OpenSSH
#NTP
ufw allow ntp
#remote access to metserver (or gromet) on port 50001
ufw allow 50001
#anywhere from subnet
ufw allow from 192.168.4.0/24
#RDBE multicast to addresses from subnet
ufw allow in proto udp to 239.0.2.0/24 from 192.168.4.0/24
#? RDBE multicast to group from subnet ?
#ufw allow in proto igmp to 239.0.2.0/24 from 192.168.4.0/24
....

=== Customize root's .bashrc file

There are a few changes you should consider for _root_'s _.bashrc_ file.

1. If you have applied the CIS remediations, you should consider
uncommenting the line that sets the `umask` to `022`. The remediations
set it to `027` in _/etc/profile_, which may cause problems with
routinely created files, including some in this section covering optional changes.

2. Uncomment the the `alias` commands that add the `-i` option to the
commands _cp_, _mv_, and _rm_ as the default.  This can help avoid
some careless errors.

3. Add the command `set -o noclobber` to avoid accidently overwriting
existing files with I/O redirection. Other options to consider setting
are `physical` and `ignoreeof`.

=== Create root's .inputrc file

The _readline_ package is used by _bash_, and other programs, to
maintain a history of commands that can be edited and then
re-executed. By default, it will retain edits of history entries that
have _not_ been re-executed. This makes the unedited history entries
more difficult to locate and re-execute. Retaining the un-executed
edits can be disabled for _root_ by creating the file:

./root/.inputrc
[source]
----
$include /etc/inputrc
set revert-all-at-newline on
----

The `$include /etc/inputrc` line preserves the other system wide
_readline_ defaults.

NOTE: The standard fresh FS installation creates this file for the
_oper_ and _prog_ (and AUID) accounts.

=== Setup /etc/hosts

You may want to add more hosts to the _/etc/hosts_, especially if do
not have DNS. This will allow you to give a short alias to use when
referring to other local machines. Even if you have DNS, you may wish
to add additional aliases for your local hosts.

For use with `ntpq -p`, is recommended that you use a short alias as
the _canonical name_ (the first one after the IP address) for other
local machines (and possibly remote ones as well). This will make the
_ntpq_ output easier to understand, particularly if the canonical
names of the local machines only differ at the end of their names.
That may make the differences hard to see given the short field
available for the `remote` node ID in the _ntpq_ output.

=== Stabilize network configuration

This subsection requires using _nm-connection-editor_ on a graphic
display (_nmtui_ may be an option on a text terminal, but it has not
been fully verified). You may need to be _root_ or _desktop_ to do
this. All the subsections below assume you are in the program and have
sufficient permissions.

NOTE: If you someday move the disks to a computer with a different
mainboard model, the device names of the network interfaces may
change. If that happens, you will need to reselect the names as
described in the sub-steps below. This should not be necessary if the
other computer uses the same mainboard.

==== Make the connection always appear on the same interface regardless of the MAC address.

This is useful both to make the connection appear on only one
interface and/or make it the same interface if the computer (or NIC)
is changed.

. Select your connection and click the "`gear`" icon.

. Select the `Ethernet` tab.

. Use the drop-down for the `Device` field to select your device
(typically `eno1` with the MAC address in parentheses). Then edit the
field to just list the name of the interface (typically `eno1`) by
removing the MAC address in parentheses.

. You may want to also set the `IPv6 Settings` to use `Method:
Disabled`.

. Click `Save`.

. Close the window by pressing kbd:[Esc] (while the focus is on that
window).

==== Disable the second Ethernet port

This may be useful, for example, if your second port has a IPMI
interface and the kernel detected a connection there and it is
interfering with the normal or the IPMI connection.

. If there is no `Wired connection 2`, click the `+` icon. Otherwise
select that connection, click the "`gear`" icon, and skip to step 4.
It _may_ be benign to delete (`-` icon) any other connections _except_
`Wired connection 1`.

. Make sure `Ethernet` is selected in the drop down box and click
`Create...`.

. Change the `Connection name` to `Wired connection 2`.

. Select the `Ethernet` tab.

. Use the drop-down for the `Device` field to select your device
(typically `eno2` with the MAC address in parentheses). Then edit the
field to just list the name of the interface (typically `eno2`) by
removing the MAC address in parentheses.

. Select the `IPv4 Settings` tab.

. For `Method` select `Disabled`.

. Select the `IPv6 Settings` tab.

. For `Method` select `Disabled`.

. Click `Save`.

. Close the window by pressing kbd:[Esc] (while the focus is on that
window).

=== Disable Desktop User

If you do not need the functionality available in the Desktop
environment, you can disable the _desktop_ account. You can re-enable
the account later if you need it. To disable it, execute:

....
usermod -L desktop
....

You can undo this by using the `-U` option instead.

To prevent connecting with _ssh_ using a key, create (or add _desktop_
to an existing) `DenyUsers` line in _/etc/ssh/sshd_config_:

....
DenyUsers desktop
....

And restart _sshd_ with:

....
systemctl restart sshd
....

You can undo the _ssh_ block  be removing the line (if it only has
_desktop_) or removing _desktop_ from the line and then restarting
_sshd_.

=== Remove ModemManager package

If you use serial ports, it is strongly advised that you remove the
ModemManager package to avoid conflicts over access to the ports.
Execute this command:

....
apt-get purge modemmanager
....

=== Remove anacron package

If you enabled the weekly update job in _fsadapt_ (it is strongly
recommended), we recommend that you also remove the _anacron_ package
so that the job will run at a fixed time every week, even if the
system is turned off for some periods of time.  Execute this
command:

....
apt-get purge anacron
....

=== Configure e-mail

The configuration described here (`Internet site` or `mail sent by
smarthost` in the _exim4_ configuration, no incoming mail, reply-to
filter, and modified user names), provides good support for system
messages and the FS _msg_ and _rdbemsg_ utilities.

. As `root`, enter:

 dpkg-reconfigure exim4-config

+

to change the setup. Typically you should select `internet site`, use
your host name in place of _debian_ when it occurs, and otherwise
select defaults at all the other prompts. (The only other recommended
choices are `local delivery only` or `mail sent by smarthost; received
via SMTP or fetchmail`.) If you want to receive incoming mail, you
will also need to enable SMTP connections in `Window 4` of _fsadapt_
(and if you are using a firewall, you will need to enable such
connections for it). We recommend that you NOT receive incoming mail
on this computer.

. <<replyfilter,Reply-To filter>>[[replyfilter]]: If you follow the
recommendation not to receive incoming mail and your system is not
setup for `local delivery only`, you should set the `Reply-To` address
for outgoing messages to a real e-mail account at your institution
that is read regularly. You can do this by (all as _root_):

+

.. Create the filter (four lines in file):

+

+

[subs="+quotes"]
....
cat >/etc/exim4/reply-to-filter <<EOF
# Exim filter          << THIS LINE REQUIRED

headers remove "Reply-To"
headers add "Reply-To: _email@address_"
EOF
....

+

Change `_email@address_` to the e-mail address you want replies to be
addressed to. If you want more than one, separate them with commas.

+

.. Create a file for local customizations:

 touch /etc/exim4/conf.d/main/00-exim-localmacros
 ln -sfn /etc/exim4/conf.d/main/00-exim-localmacros /etc/exim4/exim4.conf.localmacros

+

NOTE: The file is constructed this way so that it will work for both
non-split or split _exim4_ configurations.

.. Add a call to the filter to _/etc/exim4/exim4.conf.localmacros_:

 cat >>/etc/exim4/exim4.conf.localmacros <<EOF
 #set reply to
 system_filter = /etc/exim4/reply-to-filter
 EOF

+

.. Then execute

 update-exim4.conf
 systemctl restart exim4

. You should change your _/etc/aliases_ so _root_ and _prog_ e-mail goes to _oper_.

+
--
*    change `root: desktop` to `root: oper`
*    add `prog: oper`
*    add `desktop: oper`
--
+

This is recommended as a "`catch all`" since the _oper_ account is
presumably under regular use and any messages sent there are likely to
be noticed. This is particularly important for system error messages
since they should be delivered to a mail box on the system in case
there is a network problem that might prevent them from being
delivered off system. You can however add additional off machine
delivery of these messages to whatever addressees you wish and we
recommend this as well. These should include an e-mail account at your
institution that is read regularly (maybe the same address as the
`Reply-To` address you may have set above would be a good choice).  To
do this, create a _.forward_ file in _oper_'s home directory. The
permissions should be `-rw-r--r--`. The contents should be similar to
(left justified):

    \oper
    user@node.domain

+

where `user@node.domain` is the off machine addressee you
want the messages to go to.  You can add additional lines for
additional addressees. The backslash (`\`) before `oper`
prevents the mail system from getting into an infinite loop
re-checking _oper_'s _.forward_ file.

+

. If you have made the above changes to forward messages to another an
e-mail account on another machine, you should customize the User Name
(not login name, the User Name is the fifth field) of _root_, _prog_,
  _oper_, and _desktop_ in _/etc/passwd_ to identify the source of the
  message.  For _root_ and _prog_, it is recommended to append a
  string like `at node` (it is probably best to avoid FQDNs), where
  node is this machine, e.g., for _atri_ you might change the 5th
  field for _root_ from

    root

+

to

    root at atri

+

For _oper_, you might instead prepend your site name to the
accounts for clearer reading in `ops` e-mail messages, e.g.,
for _oper_ on _atri_ at GSFC, we changed the 5th field for
_oper_ to:

    GSFC VLBI Operator

+

and for completeness, for _prog_ and _desktop_ we use:

    GSFC VLBI Programmer
    GSFC Desktop User

+

These changes will help the recipient (possibly you)
determine which system generated this message since it may
not be obvious given the modified return address.

. To give _oper_ an indication at login that there is mail to read, add
either (to get a count of messages):
+
     test ! -f /var/mail/oper || from -c
+
or (to see the senders and subjects):
+
     test ! -f /var/mail/oper || from
+
to end of _oper_'s _.profile_ file (if using _bash_ as the login
shell) or _.login_ file (_tcsh_).

. Lastly, check the default mailbox directory _/var/mail/_ for
accounts that may have messages that arrived before the e-mail
system was fully configured.  Be sure to resolve any system
messages that may have been received. You can check to see what
accounts have mail with:
+
    ls /var/mail
+
which will list each user account mail file that
exists. Check and clear each user's mailbox (where `_user_` in
the line below is the account name) that has received mail
(as _root_):
+
[subs="+quotes"]
....
mail -f /var/mail/_user_
....
+

+

If there are messages in the _desktop_ user's mailbox that you want to
preserve and _oper_'s mailbox is empty or non-existent, you could
consider renaming _desktop_'s mailbox to be _oper_'s. If you do so, be
sure to change the owner of the file to be _oper_.

=== Generate FQDN in HELO for outgoing mail

If mail from your system is being rejected by some servers because
_exim4_ is not providing a Fully Qualified Domain Name (FQDN), in its `HELO`
message, the following steps should fix the problem.


. If you have not already created
_/etc/exim4/conf.d/main/00-exim-localmacros_ (see
<<replyfilter,Reply-To filter>> above), do so:

 touch /etc/exim4/conf.d/main/00-exim-localmacros
 ln -sfn /etc/exim4/conf.d/main/00-exim-localmacros /etc/exim4/exim4.conf.localmacros

. Add the necessary line to the file:

 cat >>/etc/exim4/exim4.conf.localmacros <<EOF
 MAIN_HARDCODE_PRIMARY_HOSTNAME=ETC_MAILNAME
 EOF

. Then execute:

 update-exim4.conf
 systemctl restart exim4

. Verify that the change has taken effect:

 exim4 -bP primary_hostname

=== Set X display resolution at boot

If your display sometimes starts with the wrong resolution, you may be
able to configure a better resolution. The following is a description
of something that worked for at least one system. The details of your
system may require some changes (beyond the resolution and output name).

First you need to determine the correct resolution and output name.
You may be able to do this with _xrandr_. If the screen currently has
the correct resolution, you can just execute:
....
xrandr
....

The output might look like:
....
Screen 0: minimum 320 x 200, current 1920 x 1200, maximum 1920 x 2048
VGA-1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1024x768      60.00
   800x600       60.32    56.25
   640x480       59.94
  1920x1200 (0x42) 154.000MHz +HSync -VSync
        h: width  1920 start 1968 end 2000 total 2080 skew    0 clock  74.04KHz
        v: height 1200 start 1203 end 1209 total 1235           clock  59.95Hz
....

Where the current screen resolution is `1920x1200` and the output name is `VGA-1`.

You can then generate the needed `Modeline` by executing:

....
cvt 1920 1200
....

Which might generate output:

....
# 1920x1200 59.88 Hz (CVT 2.30MA) hsync: 74.56 kHz; pclk: 193.25 MHz
 Modeline "1920x1200_60.00"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
....

As a test, you can make a script (use an appropriate name), that will
enable that resolution. Use the output name (`VGA-1` in this example)
and the tokens following  `Modeline` from above. There are three lines
after the `#!/bin/bash` line.

.~/display_1920x1200
[source,bash]
----
#!/bin/bash
xrandr --newmode "1920x1200_60.00"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
xrandr --addmode VGA-1 1920x1200_60.00
xrandr --output VGA-1 --mode "1920x1200_60.00"
----

Be sure to `*chmod u+x*` the file before executing.

If that is successful, you can use output name (`VGA-1` in this
example) and `Modeline` from above to make a file (you may need to create
  the directory first):

./etc/X11/xorg.conf.d/10-monitor.conf 
[source]
----
Section "Monitor"
Identifier     "VGA-1"
Option         "Enable" "true"
Modeline "1920x1200_60.00"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
EndSection

Section "Screen"
Identifier     "Screen0"
Device         "Device0"
Monitor        "VGA-1"
DefaultDepth    24
#Option         "TwinView" "0"
SubSection "Display"
    Depth          24
    Modes          "1920x1200_60.00"
EndSubSection
EndSection
----

You should _chmod_ the permissions for directory with `o+rx` and the
file with `o+r`, if those are not already set.

You could then try restarting the display (after closing all windows) with:
....
systemctl restart gdm3
....

or rebooting.

=== Use KeepAlive to prevent VLAN firewall inactivity time-out

If there is a VLAN firewall in use on the local network, it may be
necessary to use `KeepAlive` for TCP connections to prevent inactivity
time-outs for network connections from the FS to the VLBI equipment
when no activity is occurring with the system. For some devices, having
the time-out break the connection may cause an issue with the number of
connections available.

To use `KeepAlive` to prevent the inactivity time-outs, first install
the package _libkeepalive0_:

....
apt-get install libkeepalive0
....

Then add the follow lines for _oper_ (and _prog_):

.~/.profile
[source,bash]
....
export KEEPCNT=20
export KEEPIDLE=180
export KEEPINTVL=60
....

Then add the following alias for _oper_ (and _prog_):

.~/.bash_aliases
[source,bash]
----
alias fs='LD_PRELOAD=libkeepalive.so fs'
----

You will need to terminate the FS, log out, and log back in to activate these changes.

NOTE: If you run the FS from a script, you will need to include the
setting of `LD_PRELOAD` explicitly in the script since scripts do not
pick up aliases.

A similar alias can used to allow other individual applications
to avoid the inactivity time-outs. (A better
solution is available for _ssh_, discussed below.) It is also possible to put
_export{nbsp}LD_PRELOAD=libkeepalive.so_ in _~/.profile_ to enable it for all
applications, but this may generate some error messages (in the case of
_xterm_ at least, the error is apparently benign).

If you need to have a persistent _ssh_ connection, add the follow for _oper_ (and _prog_):

.~/.ssh/config file:
[source]
----
Host *
    ServerAliveInterval 200
    ServerAliveCountMax 2
----

This can be set selectively per remote system.  The interval of `200`
seconds is chosen to be less than the `300` seconds that some (possibly
security hardened) servers may use.

If not already set correctly, set the _~/.ssh/config_ file's
permissions and ownership for _oper_ (analogously for _prog_) with:

[source,bash]
----
chmod 644 ~oper/.ssh/config
chown oper.rtx ~oper/.ssh/config
----

=== Remove login banners for commands run by ssh on remote systems

If you use _ssh_ as _oper_ (and maybe _prog_), to run commands on
other systems as part of FS operations, you may get login banners
mixed in with the output.  You can suppress the banners by adding the
following for _oper_ (and analogously for _prog_):

.~/.ssh/config file:
[source]
----
Host *
    LogLevel ERROR
----

This will allow errors to be displayed while suppressing the login
banners of remote systems. This can be set selectively per remote
system.

Please check the end of the <<Use KeepAlive to prevent VLAN firewall inactivity time-out>>
section for setting the ownership and  permissions on _~/.ssh/config_.

=== Suspend, shutdown, and restart issues

. Mouse cursor disappearing on text console after suspend

+

The FSL11 installation disables suspend by default (as part of the
`greeter` item in the <<FS Adaptation: Setup (Window 2)>> sub-step of
<<_fsadapt>> in the <<Third stage installation>>). If you did not
disable suspend, you may encounter this issue. A way to fix it is to
switch to a different text console and then back again. The cursor
should reappear.

. Disable the power switch from shutting the system down

+

.. Add the following to the _/etc/gdm3/greeter.dconf-defaults_ file:

 # Disable restart buttons
 disable-restart-buttons=true

.. Restart _gdm3_:

 systemctl restart gdm3

. Disable use of restart for ordinary users

+

It is possible to disable all use of restart for ordinary users with a
bit more work -- the details are available on request. The file
link:powerlock.tar.gz[] may be helpful for this. It contains sample
contents of the files that need to be changed or created.

=== Printer setup

. Make sure your printer is connected, to the computer or the network, as appropriate.
+
TIP: Newer computers usually do not have a parallel port
(IEEE 1284).  If not, and your printer requires a
parallel connection, you should be able to obtain a
USB/Parallel converter for less than US$20.

. Login in to the X-display or remotely using an X-capable display.

. Start _firefox_

. Enter URL: `*localhost:631*`

. Select `Add printers and classes`.
+

You may be prompted to enter credentials. If your account is a member
of the _lpadmin_ group, you can use your own credentials; if not, those of the
_root_ account or another account that is a member of _lpadmin_ will be required.

. Add your printers.
+
Connected printers may be automatically offered to be added.  You may
also be able to find printers using the `Find Printer` function. If
CUPS offers you the wrong type of printer to be automatically added or
it is unclear what driver to select for a printer, you may be able to
get some useful information to help with manually installing your
printer by searching the Internet for the string `cups` and your
printer model.
+
Some printers will work with an `AppSocket/HP JetDirect` connection of the form `socket://__hostname__`.

. Be sure to select a printer as the default (usually by selecting
`Printers` at the top of the page, then select the printer to be set as the
default, then from the `Administration` drop down: `Set As Server Default`).

. Quit _firefox_

=== NTP configuration

For good performance with NTP, please follow the recommendations in
_/usr2/fs/misc/ntp.txt_.

Additionally, to make the `ntpq -c pe` output more readable for local
devices, you can adjust the contents of _/etc/hosts_. The local
devices should be listed in the file, but use a nickname (15
characters or less) that is meaningful locally in place of the
canonical name (the first name after the IP address). The canonical
name can be listed after the nickname.

=== Add raid-events scripts

If your system is using a RAID configuration, you may want to install
the _raid-events_ script. The script provides email notifications of
when Rebuilds (and array checks) start and end. For full details on
the script and installation instructions, please see the
<<raid.adoc#_raid_events,raid-events>> subsection in the
<<raid.adoc#_script_descriptions,Script descriptions>> section of the
<<raid.adoc#,RAID Notes for FSL 11>> document.

=== Add refresh_spare_usr2

If you are using two systems, an _operational_ and a _spare_, you may
want to install the _refresh_spare_usr2_ script. The script can be
used to backup the _/usr2_ partition on the _operational_ system to
the _spare_ system. For full details on the script and installation
instructions, please see the
<<raid.adoc#_refresh_spare_usr2,refresh_spare_usr2>> subsection in the
<<raid.adoc#_script_descriptions,Script descriptions>> section of the
<<raid.adoc#,RAID Notes for FSL 11>> document.

:sectnumlevels: 3
[appendix]

== Managing Security Updates

It is strongly recommended that you use the weekly _cron_ update
download (the "`weekly _cron_ job`") as configured according to the
`Window 2` subsection in the <<_fsadapt>> section above. This will
keep you informed of the available updates on a weekly basis.

It is also recommended that you remove _anacron_ as described in the
<<_remove_anacron_package>> section below. This will cause the updates
to always be downloaded at what should be innocuous time, early Sunday
morning (but this can be adjusted if need be).

NOTE: An optional method for identifying available  updates without using
the weekly _cron_ job is described below in the section
<<Manually checking for updates>>.

=== Installing updates (upgrading)

TIP: It is recommended that a disk rotation be performed before any
update is installed. This will make recovery much easier if a problem with the
update is discovered.  Please see the FSL11 Raid document section
<<raid.adoc#_recoverable_testing,Recoverable testing>> for a
streamlined method to manage testing of updates.

If updates are needed, the weekly _cron_ job will send a message to _root_
(or whoever e-mail to _root_ is aliased to, typically _oper_) with
instructions on how to install the updates. You can choose a
convenient time, when not in (or about to start) operations, to install
the updates and test the system.

IMPORTANT: The weekly _cron_ job message will include instructions for
handling a kernel update if one is available.  See the
<<Kernel updates>> subsection below for additional considerations for
kernel updates.

The commands for installing the updates given by the message are (note
        the use of _apt_ instead of _apt-get_):

   apt upgrade

Enter `*y*` to confirm as needed. Then

   apt clean

If the weekly _cron_ job was installed according to the <<_fsadapt>>
section above (for `Window 2`), the first of these commands (with
        `upgrade`) will show if any NEWS items are included in the
update. If there are, they will be displayed by a paging program at the beginning of the upgrade and
you will be given an extra chance to abort before installing.

NOTE: NEWS items are, rarely occurring, announcements that may
indicate additional steps are needed beyond the standard installation
process. If any NEWS items are displayed, you should consider
whether these will effect your system and how to handle them before
installing. The first command above (with `upgrade`) will also cause e-mails
to be sent to _root_ with the NEWS information.

=== Kernel updates

WARNING: Kernel updates require extra care and testing. If you are
using a RAID, you should consider using the
<<raid.adoc#_recoverable_testing,Recoverable testing>>
procedure to give more, and easier, options for recovery in case there
is a problem.  That procedure contains special instructions for kernel
update testing.

[NOTE]
====
When a kernel update is available, you may see messages at the start of the _cron_ job output similar to:

[source,options="nowrap"]
----
apt-listchanges: Unable to retrieve changelog for package linux-headers-amd64; 'apt-get changelog' failed with: E: Version '5.10.120+1' for 'linux-headers-amd64' was not found
E: No packages found

apt-listchanges: Unable to retrieve changelog for package linux-image-amd64; 'apt-get changelog' failed with: E: Version '5.10.120+1' for 'linux-image-amd64' was not found
E: No packages found
----

and

 Calling ['apt-get', '-qq', 'changelog', 'linux-headers-amd64=5.10.120+1'] to retrieve changelog
 Calling ['apt-get', '-qq', 'changelog', 'linux-image-amd64=5.10.120+1'] to retrieve changelog

These appear to be benign. Our only advice at this time is to ignore
them.

====

If there is a kernel update available, the weekly _cron_ job output
will include a warning at the end with additional instructions
depending on which type is available.  There are two types of kernel
updates:

. ABI updates, e.g., from _4.9.0-11-amd64_ to
   _4.9.0-12-amd64_ (with _11_ and _12_ being the ABI versions), which change the kernel ABI (Application Binary
           Interface). The warning for this case is:

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    NB: The Linux kernel image is one of the packages due to be upgraded.
    NB: (The kernal ABI has changed as per the linux-latest source package above
    NB:  so all out-of-tree modules WILL NEED TO BE REBUILT after you REBOOT.)
    NB: Please allow _extra time_ for TESTING after the upgrade.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

. Non-ABI updates, which update the kernel, but do not change the
ABI. The warning for this case is:


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    NB: The Linux kernel image is one of the packages due to be upgraded.
    NB: (Upgrading will OVERWRITE the running kernel and require you to REBOOT!)
    NB: Please allow _extra time_ for TESTING after the upgrade.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Be sure to allow time to follow the instructions when planning to
install these updates.  As described in the ABI update warning, you
will need to rebuild any out-of-tree modules after rebooting for that
case. This is discussed in the <<Updating out-of-tree modules>>
subsection below.

CAUTION: In extreme circumstances, an ABI (but _not_ a non-ABI) kernel
update can be deferred to a later date when more extensive testing can
be performed by using _apt-get_ in place of _apt_ in the instructions
for installing the update. This works because an ABI update involves
new packages. The  _apt-get_ command will install the updates for existing
packages, but it will not install the new packages. While this method can
be used to install the other updates, it is not recommended since
there are presumably security patches needed for the kernel and they
are not being installed in this case.

[TIP]
====

When the kernel is upgraded, you may get messages such as:

 update-initramfs: Generating /boot/initrd.img-5.10.0-16-amd64
 W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast

These are usually benign, unless you need that firmware. If you don't,
these messages can be silenced for future upgrades by creating an
empty version of the file. For this example, enter:

 touch /lib/firmware/ast_dp501_fw.bin

====

==== Updating out-of-tree modules

When a ABI update is installed, it will be necessary to update any,
so-called, _out-of-tree_ modules that use the kernel ABI. This must be
done _after_ rebooting with the new kernel installed.

For a normal FSL11 installations, unless you have installed other
out-of-tree modules, the only module that needs to be rebuilt is the
GPIB driver (if it is installed).  You will need to recompile it (usually using _fsadapt_,
        `Window 2`, `config_gpib` only) _after_ the initial reboot
        and then (to keep these instructions simple) reboot _again_.

If you have installed other out-of-tree modules (e.g., you use a
special driver for some of your NICs), you will need to update them
appropriately _after_ the initial reboot and then (to keep these
        instructions simple) reboot _again_.

===  Recovery from a failed update

If an update fails, e.g., an updated kernel fails to boot or another problem is discovered,
you can recover as described in FSL11 RAID document
<<raid.adoc#_recoverable_testing,Recoverable testing>>
section, if you were following that method, or from a shelf disk
according to the FSL11 RAID document <<raid.adoc#_recover_from_a_shelf_disk,Recover from
a shelf disk>> section if not and you have a good shelf disk.

==== Additional recovery option for a failed ABI kernel update

For a ABI update that has failed, it is also possible to try to use
the previous kernel on the current system. For a single boot, use the
`Advanced` option in the _grub_ menu at boot and then select the
previous kernel. You can change back permanently to the previous
kernel by purging the new kernel and its headers. To do this, use:

    dpkg -l|grep linux-image
    dpkg -l|grep linux-headers

to determine the ABI version to be removed. For example, for the
first command above, you may get:

    linux-image-4.9.0-11-amd64
    linux-image-4.9.0-12-amd64

The package with _12_ would be the later version that should be purged:

    apt-get purge linux-image-4.9.0-12-amd64

Likewise with the linux-headers. For example, for the _12_ ABI
version, there will be two packages you should purge:

    linux-headers-4.9.0-12-amd64
    linux-headers-4.9.0-12-common

=== Manually checking for updates

If you do not use the weekly _cron_ job to check for updates, or if
you want to make sure you have the very latest updates when you
install them, you can run the distributed copy of the weekly update
script manually to check for updates:

    /root/fsl11/etc_cron.weekly_apt-show-upgradeable

If there is no output, there are no updates to install.

If there is output, there are updates to install. You can install them
by following the installation procedure in subsection
<<Installing updates (upgrading)>> above, except you will use the
instructions from the output of the script above instead of from the
weekly _cron_ job (the outputs should be equivalent for the same set
of updates).  Additionally, please read the following *NOTE*.

NOTE: If the weekly _cron_ job has not been installed, you may not get a
    display of NEWS items and a chance to abort when you install the updates. You
    can use the method below with the `--which=news` parameter to
    check for NEWS before installing an update.

Any NEWS items will be included in the script output along with the
packages to be updated. If you would like to see any NEWS items more
distinctly after the previous command and before installing the
updates, you can run the script again using the `--which=news` option:

    /root/fsl11/etc_cron.weekly_apt-show-upgradeable --which=news

If there are updates available and no NEWS items, you will only get
the installation instructions.

You can use this second form of running the script to check for
updates initially, if you do not need to review which updates are
available (you will still get warnings about kernel updates). As
usual, you will see no output at all if there are no updates
available.

=== End of security updates

When support for _bullseye_ ends, currently expected in May 2024,
there will be no more security updates.  At that time, the existing
packages will be migrated to the Debian archive site. This will be
visible in the output from the weekly _cron_ job script as errors that
the packages files can't be found. Two steps are needed at that time:

. If you have been using the weekly _cron_ job, it should be deleted:
+
    rm /etc/cron.weekly/apt-show-upgradeable
+
(you may need to answer `*y*` to confirm)

. Change the _/etc/apt/sources.list_ file to point to the archive
site. Although there will be no more security updates, this will enable
downloading of additional packages if they are needed. The new lines that
should replace the corresponding lines are:
+
   deb http://archive.debian.org/debian/ bullseye main contrib non-free
   deb http://archive.debian.org/debian-security bullseye/updates main contrib non-free
   deb http://archive.debian.org/debian-volatile bullseye/volatile main contrib non-free
+
And if you are using `deb-src` lines:
+
   deb-src http://archive.debian.org/debian/ bullseye main contrib non-free
   deb-src http://archive.debian.org/debian-security bullseye/updates main contrib non-free
   deb-src http://archive.debian.org/debian-volatile bullseye/volatile main contrib non-free
+
Otherwise the `deb-src` lines can be commented out (with a leading `#`).
+
In addition, if you want to install packages from more recent
distributions that have been backported to _bullseye_ you can add:
+
  deb http://archive.debian.org/debian-backports bullseye-backports main contrib non-free
+
However, the "`backports`" are not normally needed.
+
Lastly, update the index files:
+
    apt-get update
+
This may generate an error about a `Release` file having expired, but that is benign.

[appendix]

== Other Maintenance Procedures

This appendix covers additional procedures for maintaining your
system.

=== Update IP address, hostname, FQDN, and other network information

This is useful if the computer is physically moved to a different
site, its IP address changes, or its network information needs to be
updated for a different reason. This is typically not needed if you
use DHCP, though that may still require some of the changes in the
<<sysfiles,Modify other system files>> step below (please let us know
if you gain experience).

This subsection requires using _nm-connection-editor_ on a graphic
display (_nmtui_ may be an option on a text terminal, but it has not
been fully verified). You may need to be _root_ or _desktop_ to do
this. This subsection assumes you are in the program and have
sufficient permissions.

NOTE: If you move the disks to a computer with a different mainboard
model, the device names of the network interfaces may change. In that
case, you will need to reselect the names as described in the
sub-steps of the <<Stabilize network configuration>> section of the
<<Additional Setup Items>> appendix. This should not be necessary if
the origin and destination computers have the same mainboard.

. Select your connection and click the "`gear`" icon.

. Select the `IPv4 Settings` (or `IPv6 Settings` if you are using
IPv6) tab.

. Adjust your `Manual` Method configuration: `Addresses`, `DNS
Servers` (comma separated), and `Search domains`.

. Click `Save`.

. Close the window by pressing kbd:[Esc] (while the focus is on that
window).

. <<sysfiles,Modify other system files>>[[sysfiles]]:

+
Update the information as appropriate. The system may have initially
been installed with the default hostname _debian_ and no domain name.
+
./etc/hostname
+
Change your hostname
+
./etc/hosts

+

Update your IP address, FQDN (canonical name), and alias (typically
the hostname, but multiple aliases/nicknames are allowed).

+

If you moved your computer to a new LAN environment, you may also want
to update the nodes and aliases listed, see also <<Setup /etc/hosts>>.

+

./etc/networks
+
Use your local subnet (class A, B, or C) for the _localnet_ line.
+
./etc/mailname
+
Use fully qualified node name.
+
[NOTE]
====

If your system doesn't have a FQDN or you don't want to show it in
e-mail messages, you may be able to use a fake one. A FQDN may be
necessary to allow messages to be sent successfully to some remote
hosts and _mailman_ mail lists. A possible strategy for this is to
append _.net_ to the node name you use in this file and the next. The
node name in these two files can be different than the official
hostname. However, these two mail related files should be consistent.
You might consider _fs1-<xx>.net_ (or _fs2-<xx>.net_), where _<xx>_ is
your station two letter code (lower case).

====
+
./etc/exim4/update-exim4.conf.conf
+
Look for `hostnames=`, use fully qualified domain name.
+
Then execute:
+
....
update-exim4.conf
....
+
When finished, reboot.

=== Increase the size of an LVM volume

It is possible to increase the size of an LVM volume if there is
additional room available in its volume group. These instructions
assume you will be resizing a logical volume for a typical
configuration. For example, for the logical volume mounted at _/usr2_,
on RAID device _/dev/md0_, which is using _/dev/sda2_ and _/dev/sdb2_.
Additionally, example pathnames are given in the instructions below
for adjusting the size of the logical volume for _/usr2_. All these
names may be different if you want to resize a different volume and/or
your disk configuration is different.

. Preparation

.. Check that there is enough free space available.

+

Examine the output of:

 vgs

+

You can increase the size of a logical volume if the volume group
(under the `VGS` column heading) has enough free space (`VFree`
heading) for the increase. Typically, the volume group would be `vg0`.

.. Determine the `_Path_` of the logical volume you want to extend.

... Get a listing to relate the internal device-mapper pathnames
(under the `Filesystem` column heading)  and where the logical volumes
are mounted (`Mounted on` heading). For example,
_/dev/mapper/vg0-usr2_ would typically be mounted at  _/usr2_.

 df -h

... Get a listing to relate the internal device-mapper pathname (under
the `DMPath` column heading) to the logical volume `_Path_`. For
example, for _/dev/mapper/vg0-usr2_, the `_Path_` would typically be
_/dev/vg0/usr2_.

  lvdisplay -C -o lv_dm_path,lv_path

+

... For the mount point of the logical volume you want to extend,
determine the `_Path_` using the internal device-mapper pathname from
the above two sub-steps. For example, the logical volume for _/usr2_
would typically correspond to _/dev/mapper/vg0-usr2_ and the
corresponding `_Path_` would be _/dev/vg0/usr2_.

. Pre-check (optional)

+

This sub-step is not required but can be used, along with the
"`Post-check`" sub-step below, to check that the volume size changed as
expected and that no files were lost or changed
size/modification-time.

.. Get the size (under the `1G-block` column heading) of the logical
volume (`Mounted on` heading) for the volume of interest:

 df -BG

+

Record the size to compare to the results in the "`Post-check`"
sub-step below.

.. Make a listing of the files on the `_mount_point_` (include the
leading `/`) to be changed. For example, the `_mount_point_` might be
_/usr2_.

+

+
[subs="+quotes"]
....
ls -ltR _mount_point_ >/tmp/before.txt
....

. Make the change, using the `_Path_` you determined in the
"`Preparation`" sub-step above.

.. Make a backup of your system.

+

NOTE: This sub-step, and recovery in case of a problem, is much easier
if you using the FSL11 RAID system. If not, it is strongly recommended
that you make your own backup of your entire system. The remainder of
this sub-step assumes you are using a RAID, following the approach of
the <<raid.adoc#_recoverable_testing,Recoverable testing>> procedure
in the <<raid.adoc#,Raid Notes for FSL11>> document.

+

+

If you are using a RAID, you can drop the _primary_ disk out of the
RAID to save as a backup:

 drop_primary

.. Extend `_Path_`

+

For the logical volume (mount point) you want to extend, you can
either:

... Incrementally increase the size. For example, to increase `_Path_`
by 4 GB:

+
[subs="+quotes"]
....
lvextend -L+4G _Path_
....

... Set the size to a new larger total size, say 8GB:

+

+

[subs="+quotes"]
....
lvextend -L8G _Path_
....

.. Resize `_Path_`

+

IMPORTANT: Do not _interrupt_ the next command. If it is interrupted
and you are using the <<raid.adoc#_recoverable_testing,Recoverable
testing>> procedure in the <<raid.adoc#,Raid Notes for FSL11>>
document, you will need to utilize the
<<raid.adoc#_if_the_update_is_deemed_to_have_failed,If the update is
deemed to have failed>> subsection of that procedure. Otherwise, if
you are not using that procedure, you will need to use your own
recovery method.

+

+

[subs="+quotes"]
....
resize2fs _Path_
....

. Post-check (optional)

+

This sub-step is not required but can be used, if the "`Pre-check`"
sub-step above was used, to check that the new size is correct and no
files were lost or changed size/modification-time.

.. Check that the size of the logical volume (under the `Mounted on`
column heading) has the expected new size in the output of:

 df -BG

+

Compare the result to that in the "`Pre-check`" sub-step above.

.. Make a listing of the files on the `_mount_point_` (include the
leading `/`) that was changed.  For example, the `_mount_point_` might
be _/usr2_.

+
[subs="+quotes"]
....
ls -ltR _mount_point_ >/tmp/after.txt
....

.. Compare the before and after listings of the files

  diff /tmp/before.txt /tmp/after.txt

+

There should be no differences in the listings except any changes that
can explained by other expected activity that occurred since the
"`Pre-check`" sub-step above. If there was no other activity on the
logical volume, there should be no differences.

. Cleanup

+

NOTE: If you not are using the
<<raid.adoc#_recoverable_testing,Recoverable testing>> procedure in
the <<raid.adoc#,Raid Notes for FSL11>> document, you will need to use
your own methods to restore the system if there was a problem. This
step describes how to proceed if you are using the referenced
procedure.

+

There are two options:

.. If you are satisfied with the change, you can recover the RAID
with:

  recover_raid

+

This should only take a few minutes.

+

+

NOTE: The change in the volume size will not propagate to the _shelf_
disk until the next disk rotation.

.. If you are not satisfied with the change, you can try again if you
first restore the RAID using the
<<raid.adoc#_if_the_update_is_deemed_to_have_failed,If the update is
deemed to have failed>> subsection of the
<<raid.adoc#_recoverable_testing,Recoverable testing>> procedure in
the <<raid.adoc#,Raid Notes for FSL11>> document.

[appendix]

== Rescue Mode

Rescue mode is useful for repairing some problems that prevent booting
and/or logging in.

NOTE: If your computer's _setup_ utility is locked with a password, you
may need that password to select booting from your installation media.

NOTE: You should provide suitable values for your system when a
specific value is required. Values that agree with the FSL11 install
described in this document (or reasonable defaults) are shown in parentheses.

. Boot from installation media
. Select `Advanced options ...`
. Select `... Rescue mode`
+

[NOTE]
====

You could instead add parameters to the boot line (by entering kbd:[e] for UEFI or
kbd:[Tab] for BIOS on the `... Rescue mode` line instead), following the
directions in the <<Set boot options and boot installer>> section above.
This is not necessary nor usually helpful, but if you use this approach the
most useful parameters are probably `netcfg/disable_dhcp=true` and/or
`time/zone=UTC`. Use of added parameters will change the dialogue
below.

====

. Select Language (`English`)
. Select Location (`United States`)
. Select Keymap (`American English`)
. Network configuration
+

If no network is currently available (or you know that you do not need it
for the rescue), simply press kbd:[Enter] when DHCP autoconfiguration starts and
press kbd:[Enter] again for the resulting `Network autoconfiguration failed`
message. Thereafter select `Do not configure the network at this time` and
enter in the machine's hostname when prompted before continuing below.

+

If the DHCP autoconfiguration succeeds before you can stop it, you may
as well confirm the hostname and domainname and continue with the
network anyway, since you never know when it might prove useful.
(However, if you want to make sure you don't use the network, you can
 select `Go Back` and press kbd:[Enter] for the resulting `Network
 autoconfiguration failed` message.  Thereafter select `Do not
 configure the network at this time` and enter in the machine's
 hostname when prompted before continuing below.)


+

Otherwise if the DHCP autoconfiguration fails and you want to use the
network, press kbd:[Enter] for the resulting `Network autoconfiguration
failed` message. You can then select the appropriate option, most
likely `Configure network manually` and give appropriate responses to the
prompts, ultimately continuing below.

. Select time zone (`Eastern`)
+

NOTE: The selected time zone will have no effect on the timestamps
stored on the disk for any changes you may make, but will affect the displayed times you see.

. Unless you are not using Software RAID, select `Assemble RAID array`
+
Press kbd:[Space] on `Automatic` and kbd:[Enter] to continue

. Select your root file system (_/dev/vg0/root_)
. Select `Yes` to mount separate _/boot_ partition (_/boot_), unless it is corrupt
+
For UEFI boot also select `Yes` to mount separate _/boot/efi_ partition (_/boot/efi_),
unless it is corrupt

. Select _Execute a shell in /dev/vg0/root_ (or whatever your root file system is)
. Select `Continue` to enter rescue mode
. Use whatever commands are needed for your repair
+

[NOTE]
====
If you need to use the network, DNS does not appear to work by
default in recovery mode. Use of explicit IP addresses does work. If
you need to use DNS, you can make it functional by deleting the symbolic
link _/etc/resolv.conf_ and creating it as a normal file with the
nameserver information you want, e.g.:

    rm /etc/resolv.conf
    cat >>/etc/resolv.conf <<EOF
    nameserver 8.8.8.8
    EOF
====

. Use the _exit_ command to exit when done
. Select `Reboot the system`
. "`Bob's your uncle`" (i.e., you are done!)
