#!/bin/bash
#
# Copyright (c) 2024 NVI, Inc.
#
# This file is part of FSL11 Linux distribution.
# (see http://github.com/nvi-inc/fsl11).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
set -e

cd /usr/local/sbin
#
cp -a /root/fsl11/RAID/enable_spare enable_spare
chown root.root enable_spare
chmod a+r,u+wx,go-wx enable_spare
#
cp -a /root/fsl11/RAID/disable_spare disable_spare
chown root.root disable_spare
chmod a+r,u+wx,go-wx disable_spare
