#!/bin/bash
#
# Copyright (c) 2022 NVI, Inc.
#
# This file is part of FSL10 Linux distribution.
# (see http://github.com/nvi-inc/fsl11).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# For systems with GPT LVM RAID arrays, copies the partition table onto
# the second disk (if missing), rebuilds the boot sector and adds the RAID
# partition back into the array as a spare to be rebuilt.

set -e

usage() {
	echo "Usage: $0 [-A][-h][-p]"
	echo -e "  \t-h\tdisplay this help and exit"
	echo -e "  \t-p\tdisplay prgress meter if recovering"
}

PROGRESS_METER=0
while getopts "Ahp" arg; do
	case $arg in
		p)
			PROGRESS_METER=1
			;;
		h | *)
			usage
			exit 0
			;;
	esac
done

if mdadm --detail /dev/md0 2>&1 | grep -q ", degraded $" ; then
	echo "ERROR: RAID is degraded (and not recovering). Can't start rotation."
	exit 1
fi

if grep -q recovery /proc/mdstat; then
	if [ "$PROGRESS_METER" -ne 0 ]; then
		echo "(This may safely be interrupted with 'Control-C' if you don't want to wait)"
	fi
	recovery=$(grep recovery /proc/mdstat | cut -c32-)
	echo -e -n "\r$recovery"

	if [ "$PROGRESS_METER" -ne 0 ]; then
		while grep -q recovery /proc/mdstat; do
			recovery=$(grep recovery /proc/mdstat | cut -c32-)
			echo -e -n "\r$recovery"
			sleep 1;
		done
		echo -e "\nERROR: Recovery finished. You can try '$0' again without -p."
                exit 1
        else
                echo -e "\nERROR: RAID is recoverying. Can't start rotation. Try again later."
                exit 1
        fi
fi
echo "RAID not degraded and not recoverying. Shutting down for rotation."
sync;sync
sleep 1;
shutdown -h now
