#!/bin/bash
set -e
#
if ! [ $(id -u) = 0 ]; then
   echo "This script must be run as root."
   exit 1
fi
#
echo "********************************************************************"
echo "*  This is the INSTALLATION script for a AUID account              *"
echo "********************************************************************"
echo "CAUTION: This script will automatically modify some of your directories."
echo "On /usr2, an existing user home directory will renamed to user.FSL11COPY"
badans=true
while [ "$badans" = "true" ]
do
  echo -n "Enter exisiting user to update (return to exit): "
  read ans
  case "$ans" in
    prog) echo "Can't update prog "
           ;;
    oper) echo "Can't update oper "
           ;;
    *)    if  [ x$ans = x ]; then
	    exit
          elif  [ -e /usr2/$ans.FSL11COPY -o -L /usr2/$ans.FSL11COPY ]; then
	    echo "/usr2/$ans.FSL11COPY exisits, user apparently already updated"
	  elif ! [ -e /usr2/$ans -o -L /usr2/$ans ]; then
	    echo "User $ans does not have a directory on /usr2"
	  else
           badans=false
          fi
  esac
done
#
echo "Updating /usr2/$ans"
cd /usr2
mv $ans $ans.FSL11COPY
#
cd ~/fsl11/AUID/skel
find . -print|cpio -pmdu /usr2/$ans
chown -R $ans.$ans /usr2/$ans
chmod 0750 /usr2/$ans
#
echo "Adding ~oper/.profile_$ans"
cat >~oper/.profile_$ans <<EOT
echo "Applying customizations from \${BASH_SOURCE}"
EOT
chown $ans.$ans ~oper/.profile_$ans
#
echo "Adding ~oper/.bashrc_$ans"
cat >~oper/.bashrc_$ans <<EOT
echo "Applying customizations from \${BASH_SOURCE}"
EOT
chown $ans.$ans ~oper/.bashrc_$ans
#
echo "Adding ~prog/.profile_$ans"
cat >~prog/.profile_$ans <<EOT
echo "Applying customizations from \${BASH_SOURCE}"
EOT
chown $ans.$ans ~prog/.profile_$ans
#
echo "Adding ~prog/.bashrc_$ans"
cat >~prog/.bashrc_$ans <<EOT
echo "Applying customizations from \${BASH_SOURCE}"
EOT
chown $ans.$ans ~prog/.bashrc_$ans
#
#
echo "Done."
