#!/bin/bash
#
# Copyright (c) 2020, 2023 NVI, Inc.
#
# This file is part of FSL11 Linux distribution.
# (see http://github.com/nvi-inc/fsl11).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e
if ! [ $(id -u) = 0 ]; then
   echo "This script must be run as root."
   exit 1
fi
# install promotion scripts
echo "Setting up AUID RAID scripts"
cd /usr/local/bin
cp -a ~/fsl11/AUID/rotation_shutdown .
chown root:root rotation_shutdown
chmod a+rx rotation_shutdown
cp -a ~/fsl11/AUID/refresh_secondary .
chown root:root refresh_secondary
chmod a+rx refresh_secondary
echo "Done"
